from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.webhook_config import WebhookConfig
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.webhook_config import WebhookConfig  # noqa: E501

class CreateWebhookRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, organization_id=None, workspace_id=None, tenant_id=None, account_id=None, webhook=None):  # noqa: E501
        """CreateWebhookRequest - a model defined in OpenAPI

        :param organization_id: The organization_id of this CreateWebhookRequest.  # noqa: E501
        :type organization_id: str
        :param workspace_id: The workspace_id of this CreateWebhookRequest.  # noqa: E501
        :type workspace_id: str
        :param tenant_id: The tenant_id of this CreateWebhookRequest.  # noqa: E501
        :type tenant_id: str
        :param account_id: The account_id of this CreateWebhookRequest.  # noqa: E501
        :type account_id: str
        :param webhook: The webhook of this CreateWebhookRequest.  # noqa: E501
        :type webhook: WebhookConfig
        """
        self.openapi_types = {
            'organization_id': str,
            'workspace_id': str,
            'tenant_id': str,
            'account_id': str,
            'webhook': WebhookConfig
        }

        self.attribute_map = {
            'organization_id': 'organizationId',
            'workspace_id': 'workspaceId',
            'tenant_id': 'tenantId',
            'account_id': 'accountId',
            'webhook': 'webhook'
        }

        self._organization_id = organization_id
        self._workspace_id = workspace_id
        self._tenant_id = tenant_id
        self._account_id = account_id
        self._webhook = webhook

    @classmethod
    def from_dict(cls, dikt) -> 'CreateWebhookRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateWebhookRequest of this CreateWebhookRequest.  # noqa: E501
        :rtype: CreateWebhookRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def organization_id(self) -> str:
        """Gets the organization_id of this CreateWebhookRequest.


        :return: The organization_id of this CreateWebhookRequest.
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id: str):
        """Sets the organization_id of this CreateWebhookRequest.


        :param organization_id: The organization_id of this CreateWebhookRequest.
        :type organization_id: str
        """

        self._organization_id = organization_id

    @property
    def workspace_id(self) -> str:
        """Gets the workspace_id of this CreateWebhookRequest.


        :return: The workspace_id of this CreateWebhookRequest.
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id: str):
        """Sets the workspace_id of this CreateWebhookRequest.


        :param workspace_id: The workspace_id of this CreateWebhookRequest.
        :type workspace_id: str
        """

        self._workspace_id = workspace_id

    @property
    def tenant_id(self) -> str:
        """Gets the tenant_id of this CreateWebhookRequest.


        :return: The tenant_id of this CreateWebhookRequest.
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id: str):
        """Sets the tenant_id of this CreateWebhookRequest.


        :param tenant_id: The tenant_id of this CreateWebhookRequest.
        :type tenant_id: str
        """

        self._tenant_id = tenant_id

    @property
    def account_id(self) -> str:
        """Gets the account_id of this CreateWebhookRequest.


        :return: The account_id of this CreateWebhookRequest.
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id: str):
        """Sets the account_id of this CreateWebhookRequest.


        :param account_id: The account_id of this CreateWebhookRequest.
        :type account_id: str
        """

        self._account_id = account_id

    @property
    def webhook(self) -> WebhookConfig:
        """Gets the webhook of this CreateWebhookRequest.


        :return: The webhook of this CreateWebhookRequest.
        :rtype: WebhookConfig
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook: WebhookConfig):
        """Sets the webhook of this CreateWebhookRequest.


        :param webhook: The webhook of this CreateWebhookRequest.
        :type webhook: WebhookConfig
        """

        self._webhook = webhook
