from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk import util


class DeleteOrganizationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None):  # noqa: E501
        """DeleteOrganizationResponse - a model defined in OpenAPI

        :param success: The success of this DeleteOrganizationResponse.  # noqa: E501
        :type success: bool
        """
        self.openapi_types = {
            'success': bool
        }

        self.attribute_map = {
            'success': 'success'
        }

        self._success = success

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteOrganizationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteOrganizationResponse of this DeleteOrganizationResponse.  # noqa: E501
        :rtype: DeleteOrganizationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this DeleteOrganizationResponse.


        :return: The success of this DeleteOrganizationResponse.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this DeleteOrganizationResponse.


        :param success: The success of this DeleteOrganizationResponse.
        :type success: bool
        """

        self._success = success
