from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk import util


class FileEmbeddings(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, embeddings=None, model_version=None, created_at=None, updated_at=None):  # noqa: E501
        """FileEmbeddings - a model defined in OpenAPI

        :param id: The id of this FileEmbeddings.  # noqa: E501
        :type id: str
        :param embeddings: The embeddings of this FileEmbeddings.  # noqa: E501
        :type embeddings: List[float]
        :param model_version: The model_version of this FileEmbeddings.  # noqa: E501
        :type model_version: str
        :param created_at: The created_at of this FileEmbeddings.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this FileEmbeddings.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': str,
            'embeddings': List[float],
            'model_version': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'embeddings': 'embeddings',
            'model_version': 'modelVersion',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._embeddings = embeddings
        self._model_version = model_version
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'FileEmbeddings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileEmbeddings of this FileEmbeddings.  # noqa: E501
        :rtype: FileEmbeddings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this FileEmbeddings.


        :return: The id of this FileEmbeddings.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FileEmbeddings.


        :param id: The id of this FileEmbeddings.
        :type id: str
        """

        self._id = id

    @property
    def embeddings(self) -> List[float]:
        """Gets the embeddings of this FileEmbeddings.


        :return: The embeddings of this FileEmbeddings.
        :rtype: List[float]
        """
        return self._embeddings

    @embeddings.setter
    def embeddings(self, embeddings: List[float]):
        """Sets the embeddings of this FileEmbeddings.


        :param embeddings: The embeddings of this FileEmbeddings.
        :type embeddings: List[float]
        """

        self._embeddings = embeddings

    @property
    def model_version(self) -> str:
        """Gets the model_version of this FileEmbeddings.


        :return: The model_version of this FileEmbeddings.
        :rtype: str
        """
        return self._model_version

    @model_version.setter
    def model_version(self, model_version: str):
        """Sets the model_version of this FileEmbeddings.


        :param model_version: The model_version of this FileEmbeddings.
        :type model_version: str
        """

        self._model_version = model_version

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this FileEmbeddings.


        :return: The created_at of this FileEmbeddings.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this FileEmbeddings.


        :param created_at: The created_at of this FileEmbeddings.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this FileEmbeddings.


        :return: The updated_at of this FileEmbeddings.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this FileEmbeddings.


        :param updated_at: The updated_at of this FileEmbeddings.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
