from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.account1 import Account1
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.account1 import Account1  # noqa: E501

class GetAccountResponse1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, account=None):  # noqa: E501
        """GetAccountResponse1 - a model defined in OpenAPI

        :param account: The account of this GetAccountResponse1.  # noqa: E501
        :type account: Account1
        """
        self.openapi_types = {
            'account': Account1
        }

        self.attribute_map = {
            'account': 'account'
        }

        self._account = account

    @classmethod
    def from_dict(cls, dikt) -> 'GetAccountResponse1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAccountResponse1 of this GetAccountResponse1.  # noqa: E501
        :rtype: GetAccountResponse1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account(self) -> Account1:
        """Gets the account of this GetAccountResponse1.


        :return: The account of this GetAccountResponse1.
        :rtype: Account1
        """
        return self._account

    @account.setter
    def account(self, account: Account1):
        """Sets the account of this GetAccountResponse1.


        :param account: The account of this GetAccountResponse1.
        :type account: Account1
        """

        self._account = account
