from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.lead import Lead
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.lead import Lead  # noqa: E501

class GetLeadResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lead=None):  # noqa: E501
        """GetLeadResponse - a model defined in OpenAPI

        :param lead: The lead of this GetLeadResponse.  # noqa: E501
        :type lead: Lead
        """
        self.openapi_types = {
            'lead': Lead
        }

        self.attribute_map = {
            'lead': 'lead'
        }

        self._lead = lead

    @classmethod
    def from_dict(cls, dikt) -> 'GetLeadResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetLeadResponse of this GetLeadResponse.  # noqa: E501
        :rtype: GetLeadResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lead(self) -> Lead:
        """Gets the lead of this GetLeadResponse.


        :return: The lead of this GetLeadResponse.
        :rtype: Lead
        """
        return self._lead

    @lead.setter
    def lead(self, lead: Lead):
        """Sets the lead of this GetLeadResponse.


        :param lead: The lead of this GetLeadResponse.
        :type lead: Lead
        """

        self._lead = lead
