from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.organization import Organization
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.organization import Organization  # noqa: E501

class GetOrganizationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, organization=None):  # noqa: E501
        """GetOrganizationResponse - a model defined in OpenAPI

        :param organization: The organization of this GetOrganizationResponse.  # noqa: E501
        :type organization: Organization
        """
        self.openapi_types = {
            'organization': Organization
        }

        self.attribute_map = {
            'organization': 'organization'
        }

        self._organization = organization

    @classmethod
    def from_dict(cls, dikt) -> 'GetOrganizationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetOrganizationResponse of this GetOrganizationResponse.  # noqa: E501
        :rtype: GetOrganizationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def organization(self) -> Organization:
        """Gets the organization of this GetOrganizationResponse.


        :return: The organization of this GetOrganizationResponse.
        :rtype: Organization
        """
        return self._organization

    @organization.setter
    def organization(self, organization: Organization):
        """Sets the organization of this GetOrganizationResponse.


        :param organization: The organization of this GetOrganizationResponse.
        :type organization: Organization
        """

        self._organization = organization
