from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.workspace_sharing import WorkspaceSharing
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.workspace_sharing import WorkspaceSharing  # noqa: E501

class ListWorkspaceSharingsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sharings=None, next_page_token=None, total_size=None):  # noqa: E501
        """ListWorkspaceSharingsResponse - a model defined in OpenAPI

        :param sharings: The sharings of this ListWorkspaceSharingsResponse.  # noqa: E501
        :type sharings: List[WorkspaceSharing]
        :param next_page_token: The next_page_token of this ListWorkspaceSharingsResponse.  # noqa: E501
        :type next_page_token: str
        :param total_size: The total_size of this ListWorkspaceSharingsResponse.  # noqa: E501
        :type total_size: int
        """
        self.openapi_types = {
            'sharings': List[WorkspaceSharing],
            'next_page_token': str,
            'total_size': int
        }

        self.attribute_map = {
            'sharings': 'sharings',
            'next_page_token': 'nextPageToken',
            'total_size': 'totalSize'
        }

        self._sharings = sharings
        self._next_page_token = next_page_token
        self._total_size = total_size

    @classmethod
    def from_dict(cls, dikt) -> 'ListWorkspaceSharingsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListWorkspaceSharingsResponse of this ListWorkspaceSharingsResponse.  # noqa: E501
        :rtype: ListWorkspaceSharingsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sharings(self) -> List[WorkspaceSharing]:
        """Gets the sharings of this ListWorkspaceSharingsResponse.


        :return: The sharings of this ListWorkspaceSharingsResponse.
        :rtype: List[WorkspaceSharing]
        """
        return self._sharings

    @sharings.setter
    def sharings(self, sharings: List[WorkspaceSharing]):
        """Sets the sharings of this ListWorkspaceSharingsResponse.


        :param sharings: The sharings of this ListWorkspaceSharingsResponse.
        :type sharings: List[WorkspaceSharing]
        """

        self._sharings = sharings

    @property
    def next_page_token(self) -> str:
        """Gets the next_page_token of this ListWorkspaceSharingsResponse.


        :return: The next_page_token of this ListWorkspaceSharingsResponse.
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token: str):
        """Sets the next_page_token of this ListWorkspaceSharingsResponse.


        :param next_page_token: The next_page_token of this ListWorkspaceSharingsResponse.
        :type next_page_token: str
        """

        self._next_page_token = next_page_token

    @property
    def total_size(self) -> int:
        """Gets the total_size of this ListWorkspaceSharingsResponse.


        :return: The total_size of this ListWorkspaceSharingsResponse.
        :rtype: int
        """
        return self._total_size

    @total_size.setter
    def total_size(self, total_size: int):
        """Sets the total_size of this ListWorkspaceSharingsResponse.


        :param total_size: The total_size of this ListWorkspaceSharingsResponse.
        :type total_size: int
        """

        self._total_size = total_size
