from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.account import Account
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.account import Account  # noqa: E501

class ListAccountsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, accounts=None, next_page_number=None):  # noqa: E501
        """ListAccountsResponse - a model defined in OpenAPI

        :param accounts: The accounts of this ListAccountsResponse.  # noqa: E501
        :type accounts: List[Account]
        :param next_page_number: The next_page_number of this ListAccountsResponse.  # noqa: E501
        :type next_page_number: int
        """
        self.openapi_types = {
            'accounts': List[Account],
            'next_page_number': int
        }

        self.attribute_map = {
            'accounts': 'accounts',
            'next_page_number': 'nextPageNumber'
        }

        self._accounts = accounts
        self._next_page_number = next_page_number

    @classmethod
    def from_dict(cls, dikt) -> 'ListAccountsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListAccountsResponse of this ListAccountsResponse.  # noqa: E501
        :rtype: ListAccountsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def accounts(self) -> List[Account]:
        """Gets the accounts of this ListAccountsResponse.


        :return: The accounts of this ListAccountsResponse.
        :rtype: List[Account]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts: List[Account]):
        """Sets the accounts of this ListAccountsResponse.


        :param accounts: The accounts of this ListAccountsResponse.
        :type accounts: List[Account]
        """

        self._accounts = accounts

    @property
    def next_page_number(self) -> int:
        """Gets the next_page_number of this ListAccountsResponse.


        :return: The next_page_number of this ListAccountsResponse.
        :rtype: int
        """
        return self._next_page_number

    @next_page_number.setter
    def next_page_number(self, next_page_number: int):
        """Sets the next_page_number of this ListAccountsResponse.


        :param next_page_number: The next_page_number of this ListAccountsResponse.
        :type next_page_number: int
        """

        self._next_page_number = next_page_number
