from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk.models.tenant import Tenant
from playbookmedia_backend_server_sdk import util

from playbookmedia_backend_server_sdk.models.tenant import Tenant  # noqa: E501

class ListTenantsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tenants=None, next_page_number=None):  # noqa: E501
        """ListTenantsResponse - a model defined in OpenAPI

        :param tenants: The tenants of this ListTenantsResponse.  # noqa: E501
        :type tenants: List[Tenant]
        :param next_page_number: The next_page_number of this ListTenantsResponse.  # noqa: E501
        :type next_page_number: int
        """
        self.openapi_types = {
            'tenants': List[Tenant],
            'next_page_number': int
        }

        self.attribute_map = {
            'tenants': 'tenants',
            'next_page_number': 'nextPageNumber'
        }

        self._tenants = tenants
        self._next_page_number = next_page_number

    @classmethod
    def from_dict(cls, dikt) -> 'ListTenantsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListTenantsResponse of this ListTenantsResponse.  # noqa: E501
        :rtype: ListTenantsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tenants(self) -> List[Tenant]:
        """Gets the tenants of this ListTenantsResponse.


        :return: The tenants of this ListTenantsResponse.
        :rtype: List[Tenant]
        """
        return self._tenants

    @tenants.setter
    def tenants(self, tenants: List[Tenant]):
        """Sets the tenants of this ListTenantsResponse.


        :param tenants: The tenants of this ListTenantsResponse.
        :type tenants: List[Tenant]
        """

        self._tenants = tenants

    @property
    def next_page_number(self) -> int:
        """Gets the next_page_number of this ListTenantsResponse.


        :return: The next_page_number of this ListTenantsResponse.
        :rtype: int
        """
        return self._next_page_number

    @next_page_number.setter
    def next_page_number(self, next_page_number: int):
        """Sets the next_page_number of this ListTenantsResponse.


        :param next_page_number: The next_page_number of this ListTenantsResponse.
        :type next_page_number: int
        """

        self._next_page_number = next_page_number
