from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from playbookmedia_backend_server_sdk.models.base_model import Model
from playbookmedia_backend_server_sdk import util


class OutputFormat(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    OUTPUT_FORMAT_UNSPECIFIED = 'OUTPUT_FORMAT_UNSPECIFIED'
    OUTPUT_FORMAT_JSON = 'OUTPUT_FORMAT_JSON'
    OUTPUT_FORMAT_CSV = 'OUTPUT_FORMAT_CSV'
    OUTPUT_FORMAT_BIGQUERY = 'OUTPUT_FORMAT_BIGQUERY'
    OUTPUT_FORMAT_POSTGRES = 'OUTPUT_FORMAT_POSTGRES'
    def __init__(self):  # noqa: E501
        """OutputFormat - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OutputFormat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OutputFormat of this OutputFormat.  # noqa: E501
        :rtype: OutputFormat
        """
        return util.deserialize_model(dikt, cls)
