/* tslint:disable */
/* eslint-disable */
/**
 * Lead Scraping Service API
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@vector.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface CreateAccountResponse
 */
export interface CreateAccountResponse {
    /**
     * 
     * @type {Account}
     * @memberof CreateAccountResponse
     */
    account?: Account;
}

/**
 * Check if a given object implements the CreateAccountResponse interface.
 */
export function instanceOfCreateAccountResponse(value: object): value is CreateAccountResponse {
    return true;
}

export function CreateAccountResponseFromJSON(json: any): CreateAccountResponse {
    return CreateAccountResponseFromJSONTyped(json, false);
}

export function CreateAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
    };
}

export function CreateAccountResponseToJSON(value?: CreateAccountResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': AccountToJSON(value['account']),
    };
}

