/* tslint:disable */
/* eslint-disable */
/**
 * Lead Scraping Service API
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@vector.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FieldError
 */
export interface FieldError {
  /**
   *
   * @type {string}
   * @memberof FieldError
   */
  field?: string;
  /**
   *
   * @type {string}
   * @memberof FieldError
   */
  error?: string;
}

/**
 * Check if a given object implements the FieldError interface.
 */
export function instanceOfFieldError(value: object): value is FieldError {
  return true;
}

export function FieldErrorFromJSON(json: any): FieldError {
  return FieldErrorFromJSONTyped(json, false);
}

export function FieldErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FieldError {
  if (json == null) {
    return json;
  }
  return {
    field: json['field'] == null ? undefined : json['field'],
    error: json['error'] == null ? undefined : json['error'],
  };
}

export function FieldErrorToJSON(value?: FieldError | null): any {
  if (value == null) {
    return value;
  }
  return {
    field: value['field'],
    error: value['error'],
  };
}
