/* tslint:disable */
/* eslint-disable */
/**
 * Lead Scraping Service API
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@vector.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OperationDetails
 */
export interface OperationDetails {
  /**
   *
   * @type {string}
   * @memberof OperationDetails
   */
  operationId?: string;
  /**
   *
   * @type {Date}
   * @memberof OperationDetails
   */
  startTime?: Date;
  /**
   *
   * @type {Date}
   * @memberof OperationDetails
   */
  endTime?: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof OperationDetails
   */
  stackTrace?: Array<string>;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof OperationDetails
   */
  parameters?: { [key: string]: string };
}

/**
 * Check if a given object implements the OperationDetails interface.
 */
export function instanceOfOperationDetails(
  value: object
): value is OperationDetails {
  return true;
}

export function OperationDetailsFromJSON(json: any): OperationDetails {
  return OperationDetailsFromJSONTyped(json, false);
}

export function OperationDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OperationDetails {
  if (json == null) {
    return json;
  }
  return {
    operationId: json['operationId'] == null ? undefined : json['operationId'],
    startTime:
      json['startTime'] == null ? undefined : new Date(json['startTime']),
    endTime: json['endTime'] == null ? undefined : new Date(json['endTime']),
    stackTrace: json['stackTrace'] == null ? undefined : json['stackTrace'],
    parameters: json['parameters'] == null ? undefined : json['parameters'],
  };
}

export function OperationDetailsToJSON(value?: OperationDetails | null): any {
  if (value == null) {
    return value;
  }
  return {
    operationId: value['operationId'],
    startTime:
      value['startTime'] == null ? undefined : value['startTime'].toISOString(),
    endTime:
      value['endTime'] == null ? undefined : value['endTime'].toISOString(),
    stackTrace: value['stackTrace'],
    parameters: value['parameters'],
  };
}
