/* tslint:disable */
/* eslint-disable */
/**
 * Lead Scraping Service API
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@vector.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SessionInfo
 */
export interface SessionInfo {
  /**
   *
   * @type {string}
   * @memberof SessionInfo
   */
  sessionId?: string;
  /**
   *
   * @type {Date}
   * @memberof SessionInfo
   */
  lastActive?: Date;
  /**
   *
   * @type {string}
   * @memberof SessionInfo
   */
  deviceId?: string;
  /**
   *
   * @type {string}
   * @memberof SessionInfo
   */
  ipAddress?: string;
}

/**
 * Check if a given object implements the SessionInfo interface.
 */
export function instanceOfSessionInfo(value: object): value is SessionInfo {
  return true;
}

export function SessionInfoFromJSON(json: any): SessionInfo {
  return SessionInfoFromJSONTyped(json, false);
}

export function SessionInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SessionInfo {
  if (json == null) {
    return json;
  }
  return {
    sessionId: json['sessionId'] == null ? undefined : json['sessionId'],
    lastActive:
      json['lastActive'] == null ? undefined : new Date(json['lastActive']),
    deviceId: json['deviceId'] == null ? undefined : json['deviceId'],
    ipAddress: json['ipAddress'] == null ? undefined : json['ipAddress'],
  };
}

export function SessionInfoToJSON(value?: SessionInfo | null): any {
  if (value == null) {
    return value;
  }
  return {
    sessionId: value['sessionId'],
    lastActive:
      value['lastActive'] == null
        ? undefined
        : value['lastActive'].toISOString(),
    deviceId: value['deviceId'],
    ipAddress: value['ipAddress'],
  };
}
