name = "gateway"
main = "index.ts"
compatibility_date = "2024-01-01"

# Enable the AI binding
ai = { binding = true }

# Configure KV namespaces - Comment out the ones without IDs for now
kv_namespaces = [
  { binding = "CACHE", id = "xxxx", preview_id = "xxxx" }
  # Uncomment and add proper IDs when available:
  # { binding = "AUTH_STORE", id = "your-auth-store-id", preview_id = "example_id_1" },
  # { binding = "ENRICH_KV", id = "your-enrich-kv-id", preview_id = "example_id_2" },
  # { binding = "KV", id = "your-kv-id", preview_id = "example_id_3" }
]

# Configure environment variables
[vars]
API_SECRET_KEY = "xxxx"  # Replace with actual secret key
API_KEY = ""  # Add your API key here
SECRET = ""   # Add your secret here
ENVIRONMENT = "development"

# Configure routes
routes = [
  { pattern = "api.example.com/ai*", zone_id = "xxxx" }
]

# Configure dev settings
[dev]
port = 8787
local_protocol = "http"

# Configure miniflare for local development
[miniflare]
kv_persist = true
cache_persist = true

# Configure build settings
[build]
command = "npm run build"
watch_dir = "src"

# Configure triggers
[triggers]
crons = []

# D1 Database binding
[[d1_databases]]
binding = "USERS_DATABASE"
database_name = "users"
database_id = ""  # Add your D1 database ID from Cloudflare Dashboard

# R2 Bucket binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "gateway-storage"  # Replace with your actual bucket name

# Service binding for TELLER_CERT
[[services]]
binding = "TELLER_CERT"
service = "teller-service"  # Replace with your actual service name

[env.production]
vars = { ENVIRONMENT = "production" }
# Add your production specific configuration here

[env.staging]
vars = { ENVIRONMENT = "staging" }
# Add your staging specific configuration here

[env.development]
vars = { ENVIRONMENT = "development" }
# Add your development specific configuration here 