name = ""
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
API_KEY = ""
SECRET = ""

[[d1_databases]]
binding = "USERS_DATABASE"
database_name = "users"
database_id = ""

[[kv_namespaces]]
binding = "AUTH_STORE"
id = ""

[triggers]
crons = []

[env.production]
vars = { ENVIRONMENT = "production" }
# Add your production specific configuration here

[env.staging]
vars = { ENVIRONMENT = "staging" }
# Add your staging specific configuration here

[env.development]
vars = { ENVIRONMENT = "development" }
# Add your development specific configuration here 