apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: backend-lead-scraper-service.lead-scraper-service.svc.cluster.local
  namespace: lead-scraper-service
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateWorkflow
    name: UpdateWorkflow
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListWorkflows
    name: ListWorkflows
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/TriggerWorkflow
    name: TriggerWorkflow
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/PauseWorkflow
    name: PauseWorkflow
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetWorkspaceAnalytics
    name: GetWorkspaceAnalytics
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetWorkspace
    name: GetWorkspace
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateWorkspace
    name: UpdateWorkspace
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/DeleteWorkspace
    name: DeleteWorkspace
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/CreateTenant
    name: CreateTenant
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetTenant
    name: GetTenant
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateTenant
    name: UpdateTenant
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/DeleteTenant
    name: DeleteTenant
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListTenants
    name: ListTenants
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/CreateOrganization
    name: CreateOrganization
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetOrganization
    name: GetOrganization
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateOrganization
    name: UpdateOrganization
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/DeleteOrganization
    name: DeleteOrganization
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListOrganizations
    name: ListOrganizations
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/CreateTenantAPIKey
    name: CreateTenantAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetTenantAPIKey
    name: GetTenantAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateTenantAPIKey
    name: UpdateTenantAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/DeleteTenantAPIKey
    name: DeleteTenantAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListTenantAPIKeys
    name: ListTenantAPIKeys
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/RotateTenantAPIKey
    name: RotateTenantAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/CreateAPIKey
    name: CreateAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetAPIKey
    name: GetAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateAPIKey
    name: UpdateAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/DeleteAPIKey
    name: DeleteAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListAPIKeys
    name: ListAPIKeys
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/RotateAPIKey
    name: RotateAPIKey
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListLeads
    name: ListLeads
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetLead
    name: GetLead
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/CreateWebhook
    name: CreateWebhook
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/GetWebhook
    name: GetWebhook
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/UpdateWebhook
    name: UpdateWebhook
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/DeleteWebhook
    name: DeleteWebhook
  - condition:
      method: POST
      pathRegex: /lead_scraper_service\.v1\.LeadScraperService/ListWebhooks
    name: ListWebhooks
