apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: backend-workspace-service.workspace-service.svc.cluster.local
  namespace: workspace-service
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/CreateAccount
    name: CreateAccount
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/GetAccount
    name: GetAccount
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/UpdateAccount
    name: UpdateAccount
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/DeleteAccount
    name: DeleteAccount
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/ListAccounts
    name: ListAccounts
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/CreateWorkspace
    name: CreateWorkspace
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/GetWorkspace
    name: GetWorkspace
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/UpdateWorkspace
    name: UpdateWorkspace
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/DeleteWorkspace
    name: DeleteWorkspace
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/ListWorkspaces
    name: ListWorkspaces
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/ShareWorkspace
    name: ShareWorkspace
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/UpdateWorkspaceSharing
    name: UpdateWorkspaceSharing
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/RemoveWorkspaceSharing
    name: RemoveWorkspaceSharing
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/ListWorkspaceSharings
    name: ListWorkspaceSharings
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/GetWorkspaceAnalytics
    name: GetWorkspaceAnalytics
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/GetWorkspaceComplianceReport
    name: GetWorkspaceComplianceReport
  - condition:
      method: POST
      pathRegex: /workspace_service\.v1\.WorkspaceService/GetWorkspaceStorageStats
    name: GetWorkspaceStorageStats
