version: '3'
services:
  scraping-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3003
      - BLOCK_MEDIA=false
      - NODE_ENV=development
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api-docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: nodemon
