from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from backend_server.models.base_model import Model
from backend_server.models.error_response import ErrorResponse
from backend_server import util

from backend_server.models.error_response import ErrorResponse  # noqa: E501

class TooEarlyErrorMessageResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, message=None, error_response=None):  # noqa: E501
        """TooEarlyErrorMessageResponse - a model defined in OpenAPI

        :param code: The code of this TooEarlyErrorMessageResponse.  # noqa: E501
        :type code: int
        :param message: The message of this TooEarlyErrorMessageResponse.  # noqa: E501
        :type message: str
        :param error_response: The error_response of this TooEarlyErrorMessageResponse.  # noqa: E501
        :type error_response: ErrorResponse
        """
        self.openapi_types = {
            'code': int,
            'message': str,
            'error_response': ErrorResponse
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'error_response': 'errorResponse'
        }

        self._code = code
        self._message = message
        self._error_response = error_response

    @classmethod
    def from_dict(cls, dikt) -> 'TooEarlyErrorMessageResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TooEarlyErrorMessageResponse of this TooEarlyErrorMessageResponse.  # noqa: E501
        :rtype: TooEarlyErrorMessageResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this TooEarlyErrorMessageResponse.


        :return: The code of this TooEarlyErrorMessageResponse.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this TooEarlyErrorMessageResponse.


        :param code: The code of this TooEarlyErrorMessageResponse.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this TooEarlyErrorMessageResponse.


        :return: The message of this TooEarlyErrorMessageResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this TooEarlyErrorMessageResponse.


        :param message: The message of this TooEarlyErrorMessageResponse.
        :type message: str
        """

        self._message = message

    @property
    def error_response(self) -> ErrorResponse:
        """Gets the error_response of this TooEarlyErrorMessageResponse.


        :return: The error_response of this TooEarlyErrorMessageResponse.
        :rtype: ErrorResponse
        """
        return self._error_response

    @error_response.setter
    def error_response(self, error_response: ErrorResponse):
        """Sets the error_response of this TooEarlyErrorMessageResponse.


        :param error_response: The error_response of this TooEarlyErrorMessageResponse.
        :type error_response: ErrorResponse
        """

        self._error_response = error_response
