/*
Lead Scraping Service API

Vector Lead Scraping Service API - Manages Lead Scraping Jobs

API version: 1.0
Contact: yoanyomba@vector.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package backend_client

import (
	"encoding/json"
)

// checks if the TooEarlyErrorMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TooEarlyErrorMessageResponse{}

// TooEarlyErrorMessageResponse Indicates that the server is unwilling to risk processing a request that might be replayed
type TooEarlyErrorMessageResponse struct {
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	ErrorResponse *ErrorResponse `json:"errorResponse,omitempty"`
}

// NewTooEarlyErrorMessageResponse instantiates a new TooEarlyErrorMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTooEarlyErrorMessageResponse() *TooEarlyErrorMessageResponse {
	this := TooEarlyErrorMessageResponse{}
	return &this
}

// NewTooEarlyErrorMessageResponseWithDefaults instantiates a new TooEarlyErrorMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTooEarlyErrorMessageResponseWithDefaults() *TooEarlyErrorMessageResponse {
	this := TooEarlyErrorMessageResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *TooEarlyErrorMessageResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TooEarlyErrorMessageResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *TooEarlyErrorMessageResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *TooEarlyErrorMessageResponse) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TooEarlyErrorMessageResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TooEarlyErrorMessageResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TooEarlyErrorMessageResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TooEarlyErrorMessageResponse) SetMessage(v string) {
	o.Message = &v
}

// GetErrorResponse returns the ErrorResponse field value if set, zero value otherwise.
func (o *TooEarlyErrorMessageResponse) GetErrorResponse() ErrorResponse {
	if o == nil || IsNil(o.ErrorResponse) {
		var ret ErrorResponse
		return ret
	}
	return *o.ErrorResponse
}

// GetErrorResponseOk returns a tuple with the ErrorResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TooEarlyErrorMessageResponse) GetErrorResponseOk() (*ErrorResponse, bool) {
	if o == nil || IsNil(o.ErrorResponse) {
		return nil, false
	}
	return o.ErrorResponse, true
}

// HasErrorResponse returns a boolean if a field has been set.
func (o *TooEarlyErrorMessageResponse) HasErrorResponse() bool {
	if o != nil && !IsNil(o.ErrorResponse) {
		return true
	}

	return false
}

// SetErrorResponse gets a reference to the given ErrorResponse and assigns it to the ErrorResponse field.
func (o *TooEarlyErrorMessageResponse) SetErrorResponse(v ErrorResponse) {
	o.ErrorResponse = &v
}

func (o TooEarlyErrorMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TooEarlyErrorMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ErrorResponse) {
		toSerialize["errorResponse"] = o.ErrorResponse
	}
	return toSerialize, nil
}

type NullableTooEarlyErrorMessageResponse struct {
	value *TooEarlyErrorMessageResponse
	isSet bool
}

func (v NullableTooEarlyErrorMessageResponse) Get() *TooEarlyErrorMessageResponse {
	return v.value
}

func (v *NullableTooEarlyErrorMessageResponse) Set(val *TooEarlyErrorMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTooEarlyErrorMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTooEarlyErrorMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTooEarlyErrorMessageResponse(val *TooEarlyErrorMessageResponse) *NullableTooEarlyErrorMessageResponse {
	return &NullableTooEarlyErrorMessageResponse{value: val, isSet: true}
}

func (v NullableTooEarlyErrorMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTooEarlyErrorMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


