# run directly from the repo root directory
# docker build -f ./packages/api/Dockerfile.dev .
FROM node:20-alpine3.21

# Install dependencies
RUN apk add --no-cache libc6-compat netcat-openbsd curl openssl git
RUN apk update

# Install pnpm
RUN npm install -g pnpm@8.15.1

WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Start API in development mode
CMD pnpm install && npx prisma db pull && npx prisma generate && pnpm run start:dev 