/**
 * 
 * Lead Scraping Service API
 * 
 * 
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 * 
 * Version: 1.0
 * Contact: yoanyomba@vector.ai
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// lead_scraper_service_api

export default {
    Query: {

        // @return DownloadScrapingResultsResponse
        DownloadScrapingResults: ($jobId, $userId, $orgId, $tenantId) => {
            return {
                "jobId": "jobId_example",
                "userId": "userId_example",
                "orgId": "orgId_example",
                "tenantId": "tenantId_example"
            };
        },

        // @return GetAccountResponse
        GetAccount: ($Id_) => {
            return {
                "Id_": "Id__example"
            };
        },

        // @return GetScrapingJobResponse
        GetScrapingJob: ($jobId, $userId, $orgId, $tenantId) => {
            return {
                "jobId": "jobId_example",
                "userId": "userId_example",
                "orgId": "orgId_example",
                "tenantId": "tenantId_example"
            };
        },

        // @return ListScrapingJobsResponse
        ListScrapingJobs: ($userId, $orgId, $tenantId) => {
            return {
                "userId": "userId_example",
                "orgId": "orgId_example",
                "tenantId": "tenantId_example"
            };
        },

    },

    Mutation: {

        // @return CreateAccountResponse
        CreateAccount: ($createAccountRequest) => {
            return {
                "createAccountRequest": ""
            };
        },

        // @return CreateScrapingJobResponse
        CreateScrapingJob: ($createScrapingJobRequest) => {
            return {
                "createScrapingJobRequest": ""
            };
        },

        // @return DeleteAccountResponse
        DeleteAccount: ($Id_) => {
            return {
                "Id_": "Id__example"
            };
        },

        // @return DeleteScrapingJobResponse
        DeleteScrapingJob: ($jobId, $userId, $orgId, $tenantId) => {
            return {
                "jobId": "jobId_example",
                "userId": "userId_example",
                "orgId": "orgId_example",
                "tenantId": "tenantId_example"
            };
        },

        // @return UpdateAccountResponse
        UpdateAccount: ($updateAccountRequest) => {
            return {
                "updateAccountRequest": ""
            };
        },

    }
}