apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unified-api-service.fullname" . }}-secrets
  labels:
    {{- include "unified-api-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Core settings
  JWT_SECRET: {{ .Values.env.JWT_SECRET | b64enc | quote }}
  
  # Database settings
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc | quote }}
  
  # Redis settings
  REDIS_PASS: {{ .Values.env.REDIS_PASS | b64enc | quote }}
  
  # Monitoring settings
  SENTRY_DSN: {{ .Values.env.SENTRY_DSN | b64enc | quote }}
  POSTHOG_KEY: {{ .Values.env.POSTHOG_KEY | b64enc | quote }}
  
  # Application settings
  ENCRYPT_CRYPTO_SECRET_KEY: {{ .Values.env.ENCRYPT_CRYPTO_SECRET_KEY | b64enc | quote }}
  
  # Email settings
  SMTP_USER: {{ .Values.env.SMTP_USER | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.env.SMTP_PASSWORD | b64enc | quote }}
  
  # AWS settings
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  
  # AI/ML settings
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  JINA_API_KEY: {{ .Values.env.JINA_API_KEY | b64enc | quote }}
  COHERE_API_KEY: {{ .Values.env.COHERE_API_KEY | b64enc | quote }}
  UNSTRUCTURED_API_KEY: {{ .Values.env.UNSTRUCTURED_API_KEY | b64enc | quote }}
  
  # Vector database settings
  PINECONE_API_KEY: {{ .Values.env.PINECONE_API_KEY | b64enc | quote }}
  QDRANT_API_KEY: {{ .Values.env.QDRANT_API_KEY | b64enc | quote }}
  WEAVIATE_API_KEY: {{ .Values.env.WEAVIATE_API_KEY | b64enc | quote }}
  TURBOPUFFER_API_KEY: {{ .Values.env.TURBOPUFFER_API_KEY | b64enc | quote }}
  
  # Logging settings
  AXIOM_TOKEN: {{ .Values.env.AXIOM_TOKEN | b64enc | quote }}

  # CRM Cloud Client Secrets
  HUBSPOT_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.HUBSPOT_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  ATTIO_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.ATTIO_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  ZOHO_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.ZOHO_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  PIPEDRIVE_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.PIPEDRIVE_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  ZENDESK_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.ZENDESK_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  SALESFORCE_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.SALESFORCE_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  MICROSOFTDYNAMICSSALES_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.MICROSOFTDYNAMICSSALES_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  ACCELO_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.ACCELO_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  CAPSULE_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.CAPSULE_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  CLOSE_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.CLOSE_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  COPPER_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.COPPER_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  KEAP_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.KEAP_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  TEAMLEADER_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.TEAMLEADER_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}
  TEAMWORK_CRM_CLOUD_CLIENT_SECRET: {{ .Values.env.TEAMWORK_CRM_CLOUD_CLIENT_SECRET | b64enc | quote }}

  # Ticketing Cloud Client Secrets
  ZENDESK_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.ZENDESK_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  FRONT_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.FRONT_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  CLICKUP_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.CLICKUP_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  GITHUB_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.GITHUB_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  GITLAB_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.GITLAB_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  GORGIAS_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.GORGIAS_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  JIRA_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.JIRA_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  JIRA_SERVICEMGMT_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.JIRA_SERVICEMGMT_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  LINEAR_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.LINEAR_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  AHA_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.AHA_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  WRIKE_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.WRIKE_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  ASANA_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.ASANA_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  KLAVIYO_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.KLAVIYO_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  HELPSCOUT_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.HELPSCOUT_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  IRONCLAD_TICKETING_CLOUD_CLIENT_SECRET: {{ .Values.env.IRONCLAD_TICKETING_CLOUD_CLIENT_SECRET | b64enc | quote }}

  # Accounting Cloud Client Secrets
  PENNYLANE_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.PENNYLANE_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  FRESHBOOKS_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.FRESHBOOKS_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  FREEAGENT_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.FREEAGENT_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  SAGE_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.SAGE_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  MONEYBIRD_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.MONEYBIRD_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  QUICKBOOKS_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.QUICKBOOKS_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  WAVE_FINANCIAL_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.WAVE_FINANCIAL_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}
  XERO_ACCOUNTING_CLOUD_CLIENT_SECRET: {{ .Values.env.XERO_ACCOUNTING_CLOUD_CLIENT_SECRET | b64enc | quote }}

  # Marketing Automation Cloud Client Secrets
  GETRESPONSE_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET: {{ .Values.env.GETRESPONSE_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET | b64enc | quote }}
  MAILCHIMP_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET: {{ .Values.env.MAILCHIMP_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET | b64enc | quote }}
  PODIUM_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET: {{ .Values.env.PODIUM_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET | b64enc | quote }}
  KEAP_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET: {{ .Values.env.KEAP_MARKETINGAUTOMATION_CLOUD_CLIENT_SECRET | b64enc | quote }}

  # File Storage Cloud Client Secrets
  GOOGLEDRIVE_FILESTORAGE_CLOUD_CLIENT_SECRET: {{ .Values.env.GOOGLEDRIVE_FILESTORAGE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  ONEDRIVE_FILESTORAGE_CLOUD_CLIENT_SECRET: {{ .Values.env.ONEDRIVE_FILESTORAGE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  SHAREPOINT_FILESTORAGE_CLOUD_CLIENT_SECRET: {{ .Values.env.SHAREPOINT_FILESTORAGE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  DROPBOX_FILESTORAGE_CLOUD_CLIENT_SECRET: {{ .Values.env.DROPBOX_FILESTORAGE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  BOX_FILESTORAGE_CLOUD_CLIENT_SECRET: {{ .Values.env.BOX_FILESTORAGE_CLOUD_CLIENT_SECRET | b64enc | quote }}

  # Productivity Cloud Client Secrets
  NOTION_PRODUCTIVITY_CLOUD_CLIENT_SECRET: {{ .Values.env.NOTION_PRODUCTIVITY_CLOUD_CLIENT_SECRET | b64enc | quote }}
  SLACK_PRODUCTIVITY_CLOUD_CLIENT_SECRET: {{ .Values.env.SLACK_PRODUCTIVITY_CLOUD_CLIENT_SECRET | b64enc | quote }}

  # E-commerce Cloud Client Secrets
  SHOPIFY_ECOMMERCE_CLOUD_CLIENT_SECRET: {{ .Values.env.SHOPIFY_ECOMMERCE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  SQUARESPACE_ECOMMERCE_CLOUD_CLIENT_SECRET: {{ .Values.env.SQUARESPACE_ECOMMERCE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  EBAY_ECOMMERCE_CLOUD_CLIENT_SECRET: {{ .Values.env.EBAY_ECOMMERCE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  FAIRE_ECOMMERCE_CLOUD_CLIENT_SECRET: {{ .Values.env.FAIRE_ECOMMERCE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  WEBFLOW_ECOMMERCE_CLOUD_CLIENT_SECRET: {{ .Values.env.WEBFLOW_ECOMMERCE_CLOUD_CLIENT_SECRET | b64enc | quote }}
  AMAZON_ECOMMERCE_CLOUD_CLIENT_SECRET: {{ .Values.env.AMAZON_ECOMMERCE_CLOUD_CLIENT_SECRET | b64enc | quote }} 