---
# Source: api-gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  labels:
    helm.sh/chart: api-gateway-1.0.1
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway
    app.kubernetes.io/version: "4.0.0"
    app.kubernetes.io/managed-by: Helm

