// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lead Scraping Service API
 *
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * API version: 1.0
 * Contact: yoanyomba@vector.ai
 */

package backend_server

import (
	"context"
	"net/http"
	"errors"
)

// LeadScraperServiceAPIService is a service that implements the logic for the LeadScraperServiceAPIServicer
// This service should implement the business logic for every endpoint for the LeadScraperServiceAPI API.
// Include any external packages or services that will be required by this service.
type LeadScraperServiceAPIService struct {
}

// NewLeadScraperServiceAPIService creates a default api service
func NewLeadScraperServiceAPIService() *LeadScraperServiceAPIService {
	return &LeadScraperServiceAPIService{}
}

// CreateAccount - Create a new account
func (s *LeadScraperServiceAPIService) CreateAccount(ctx context.Context, createAccountRequest CreateAccountRequest) (ImplResponse, error) {
	// TODO - update CreateAccount with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CreateAccountResponse{}) or use other options such as http.Ok ...
	// return Response(200, CreateAccountResponse{}), nil

	// TODO: Uncomment the next line to return response Response(201, CreateAccountResponse{}) or use other options such as http.Ok ...
	// return Response(201, CreateAccountResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateAccount method not implemented")
}

// CreateScrapingJob - Create a new job scraping task
func (s *LeadScraperServiceAPIService) CreateScrapingJob(ctx context.Context, createScrapingJobRequest CreateScrapingJobRequest) (ImplResponse, error) {
	// TODO - update CreateScrapingJob with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CreateScrapingJobResponse{}) or use other options such as http.Ok ...
	// return Response(200, CreateScrapingJobResponse{}), nil

	// TODO: Uncomment the next line to return response Response(201, CreateScrapingJobResponse{}) or use other options such as http.Ok ...
	// return Response(201, CreateScrapingJobResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateScrapingJob method not implemented")
}

// DeleteAccount - Delete account
func (s *LeadScraperServiceAPIService) DeleteAccount(ctx context.Context, accountId string, orgId string, tenantId string) (ImplResponse, error) {
	// TODO - update DeleteAccount with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DeleteAccountResponse{}) or use other options such as http.Ok ...
	// return Response(200, DeleteAccountResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteAccount method not implemented")
}

// DeleteScrapingJob - Delete a specific job
func (s *LeadScraperServiceAPIService) DeleteScrapingJob(ctx context.Context, jobId string, userId string, orgId string, tenantId string) (ImplResponse, error) {
	// TODO - update DeleteScrapingJob with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DeleteScrapingJobResponse{}) or use other options such as http.Ok ...
	// return Response(200, DeleteScrapingJobResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteScrapingJob method not implemented")
}

// DownloadScrapingResults - Download job results as CSV
func (s *LeadScraperServiceAPIService) DownloadScrapingResults(ctx context.Context, jobId string, userId string, orgId string, tenantId string) (ImplResponse, error) {
	// TODO - update DownloadScrapingResults with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DownloadScrapingResultsResponse{}) or use other options such as http.Ok ...
	// return Response(200, DownloadScrapingResultsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DownloadScrapingResults method not implemented")
}

// GetAccount - Get account details
func (s *LeadScraperServiceAPIService) GetAccount(ctx context.Context, accountId string, orgId string, tenantId string) (ImplResponse, error) {
	// TODO - update GetAccount with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetAccountResponse{}) or use other options such as http.Ok ...
	// return Response(200, GetAccountResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAccount method not implemented")
}

// GetScrapingJob - Get a specific job
func (s *LeadScraperServiceAPIService) GetScrapingJob(ctx context.Context, jobId string, userId string, orgId string, tenantId string) (ImplResponse, error) {
	// TODO - update GetScrapingJob with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetScrapingJobResponse{}) or use other options such as http.Ok ...
	// return Response(200, GetScrapingJobResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetScrapingJob method not implemented")
}

// ListAccounts - List accounts
func (s *LeadScraperServiceAPIService) ListAccounts(ctx context.Context, orgId string, tenantId string, offset int32, limit int32) (ImplResponse, error) {
	// TODO - update ListAccounts with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ListAccountsResponse{}) or use other options such as http.Ok ...
	// return Response(200, ListAccountsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListAccounts method not implemented")
}

// ListScrapingJobs - Get all jobs
func (s *LeadScraperServiceAPIService) ListScrapingJobs(ctx context.Context, userId string, orgId string, tenantId string) (ImplResponse, error) {
	// TODO - update ListScrapingJobs with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ListScrapingJobsResponse{}) or use other options such as http.Ok ...
	// return Response(200, ListScrapingJobsResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListScrapingJobs method not implemented")
}

// UpdateAccount - Update account details
func (s *LeadScraperServiceAPIService) UpdateAccount(ctx context.Context, updateAccountRequest UpdateAccountRequest) (ImplResponse, error) {
	// TODO - update UpdateAccount with the required logic for this service method.
	// Add api_lead_scraper_service_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UpdateAccountResponse{}) or use other options such as http.Ok ...
	// return Response(200, UpdateAccountResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ValidationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(400, ValidationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, AuthenticationErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(401, AuthenticationErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(402, PaymentRequiredErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(402, PaymentRequiredErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ForbiddenErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(403, ForbiddenErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, NotFoundErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(404, NotFoundErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(405, MethodNotAllowedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(405, MethodNotAllowedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ConflictErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(409, ConflictErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(410, GoneErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(410, GoneErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(412, PreconditionFailedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(412, PreconditionFailedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, UnprocessableEntityErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(422, UnprocessableEntityErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(425, TooEarlyErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(425, TooEarlyErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, RateLimitErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(429, RateLimitErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(500, InternalErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(500, InternalErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(501, NotImplementedErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(501, NotImplementedErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(502, BadGatewayErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(502, BadGatewayErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(503, ServiceUnavailableErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(503, ServiceUnavailableErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(504, GatewayTimeoutErrorMessageResponse{}) or use other options such as http.Ok ...
	// return Response(504, GatewayTimeoutErrorMessageResponse{}), nil

	// TODO: Uncomment the next line to return response Response(0, Status{}) or use other options such as http.Ok ...
	// return Response(0, Status{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateAccount method not implemented")
}
