// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lead Scraping Service API
 *
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * API version: 1.0
 * Contact: yoanyomba@vector.ai
 */

package backend_server




type GetScrapingJobResponse struct {

	Job ScrapingJob `json:"job,omitempty"`
}

// AssertGetScrapingJobResponseRequired checks if the required fields are not zero-ed
func AssertGetScrapingJobResponseRequired(obj GetScrapingJobResponse) error {
	if err := AssertScrapingJobRequired(obj.Job); err != nil {
		return err
	}
	return nil
}

// AssertGetScrapingJobResponseConstraints checks if the values respects the defined constraints
func AssertGetScrapingJobResponseConstraints(obj GetScrapingJobResponse) error {
	if err := AssertScrapingJobConstraints(obj.Job); err != nil {
		return err
	}
	return nil
}
