// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lead Scraping Service API
 *
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * API version: 1.0
 * Contact: yoanyomba@vector.ai
 */

package backend_server


import (
	"time"
)



type SessionInfo struct {

	SessionId string `json:"sessionId,omitempty"`

	LastActive time.Time `json:"lastActive,omitempty"`

	DeviceId string `json:"deviceId,omitempty"`

	IpAddress string `json:"ipAddress,omitempty"`
}

// AssertSessionInfoRequired checks if the required fields are not zero-ed
func AssertSessionInfoRequired(obj SessionInfo) error {
	return nil
}

// AssertSessionInfoConstraints checks if the values respects the defined constraints
func AssertSessionInfoConstraints(obj SessionInfo) error {
	return nil
}
