// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lead Scraping Service API
 *
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * API version: 1.0
 * Contact: yoanyomba@vector.ai
 */

package backend_server




// ServiceUnavailableErrorMessageResponse - Represents service availability errors
type ServiceUnavailableErrorMessageResponse struct {

	Code InternalErrorCode `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	AvailabilityInfo AvailabilityInfo `json:"availabilityInfo,omitempty"`

	ErrorResponse ErrorResponse `json:"errorResponse,omitempty"`
}

// AssertServiceUnavailableErrorMessageResponseRequired checks if the required fields are not zero-ed
func AssertServiceUnavailableErrorMessageResponseRequired(obj ServiceUnavailableErrorMessageResponse) error {
	if err := AssertAvailabilityInfoRequired(obj.AvailabilityInfo); err != nil {
		return err
	}
	if err := AssertErrorResponseRequired(obj.ErrorResponse); err != nil {
		return err
	}
	return nil
}

// AssertServiceUnavailableErrorMessageResponseConstraints checks if the values respects the defined constraints
func AssertServiceUnavailableErrorMessageResponseConstraints(obj ServiceUnavailableErrorMessageResponse) error {
	if err := AssertAvailabilityInfoConstraints(obj.AvailabilityInfo); err != nil {
		return err
	}
	if err := AssertErrorResponseConstraints(obj.ErrorResponse); err != nil {
		return err
	}
	return nil
}
