// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lead Scraping Service API
 *
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * API version: 1.0
 * Contact: yoanyomba@vector.ai
 */

package backend_server




type ServiceStatus struct {

	Name string `json:"name,omitempty"`

	Status string `json:"status,omitempty"`

	Metrics map[string]string `json:"metrics,omitempty"`

	Dependencies []Dependency `json:"dependencies,omitempty"`
}

// AssertServiceStatusRequired checks if the required fields are not zero-ed
func AssertServiceStatusRequired(obj ServiceStatus) error {
	for _, el := range obj.Dependencies {
		if err := AssertDependencyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertServiceStatusConstraints checks if the values respects the defined constraints
func AssertServiceStatusConstraints(obj ServiceStatus) error {
	for _, el := range obj.Dependencies {
		if err := AssertDependencyConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
