{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "api-gateway.serviceAccountName" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
  annotations:
    {{- include "api-gateway.annotations" . | nindent 4 }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end -}}
{{- end -}}
