apiVersion: v1
kind: Service
metadata:
  name: {{ template "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- include "api-gateway.annotations" . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
      nodePort: {{ .Values.service.metrics.nodeport }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
