/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum AccountType {
  Unspecified = <any>'ACCOUNT_TYPE_UNSPECIFIED',
  User = <any>'ACCOUNT_TYPE_USER',
  Community = <any>'ACCOUNT_TYPE_COMMUNITY',
}
