/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * The AccountingAttachment object is used to represent a company\'s attachments.
 */
export class AccountingAttachment {
  'id'?: string;
  /**
   * The third-party API ID of the matching object.
   */
  'remoteId'?: string;
  /**
   * The attachment\'s name.
   */
  'fileName'?: string;
  /**
   * The attachment\'s url.
   */
  'fileUrl'?: string;
  /**
   * The company the accounting attachment belongs to.
   */
  'company'?: string;
  'remoteWasDeleted'?: boolean;
  /**
   * Consider using google.protobuf.Timestamp if precise time manipulation is required
   */
  'modifiedAt'?: Date;
  /**
   * The third-party API ID of the matching object.
   */
  'mergeRecordId'?: string;
  'createdAt'?: Date;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'remoteId',
      baseName: 'remoteId',
      type: 'string',
    },
    {
      name: 'fileName',
      baseName: 'fileName',
      type: 'string',
    },
    {
      name: 'fileUrl',
      baseName: 'fileUrl',
      type: 'string',
    },
    {
      name: 'company',
      baseName: 'company',
      type: 'string',
    },
    {
      name: 'remoteWasDeleted',
      baseName: 'remoteWasDeleted',
      type: 'boolean',
    },
    {
      name: 'modifiedAt',
      baseName: 'modifiedAt',
      type: 'Date',
    },
    {
      name: 'mergeRecordId',
      baseName: 'mergeRecordId',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return AccountingAttachment.attributeTypeMap;
  }
}
