/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActionableInsight {
  'id'?: string;
  'detailedAction'?: string;
  'summarizedAction'?: string;
  'generatedTime'?: Date;
  'tags'?: Array<string>;
  'createdAt'?: Date;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'detailedAction',
      baseName: 'detailedAction',
      type: 'string',
    },
    {
      name: 'summarizedAction',
      baseName: 'summarizedAction',
      type: 'string',
    },
    {
      name: 'generatedTime',
      baseName: 'generatedTime',
      type: 'Date',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<string>',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return ActionableInsight.attributeTypeMap;
  }
}
