/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountType } from './accountType';
import { CommunityProfile } from './communityProfile';
import { UserProfile } from './userProfile';

export class Actor {
  'userProfile': UserProfile;
  'community': CommunityProfile;
  'actorType': AccountType;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'userProfile',
      baseName: 'userProfile',
      type: 'UserProfile',
    },
    {
      name: 'community',
      baseName: 'community',
      type: 'CommunityProfile',
    },
    {
      name: 'actorType',
      baseName: 'actorType',
      type: 'AccountType',
    },
  ];

  static getAttributeTypeMap() {
    return Actor.attributeTypeMap;
  }
}

export namespace Actor {}
