/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PollPost } from './pollPost';
import { Post } from './post';
import { SharedPost } from './sharedPost';

export class AddPostQualityScoreResponse {
  'regularPost'?: Post;
  'sharedPost'?: SharedPost;
  'pollPost'?: PollPost;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'regularPost',
      baseName: 'regularPost',
      type: 'Post',
    },
    {
      name: 'sharedPost',
      baseName: 'sharedPost',
      type: 'SharedPost',
    },
    {
      name: 'pollPost',
      baseName: 'pollPost',
      type: 'PollPost',
    },
  ];

  static getAttributeTypeMap() {
    return AddPostQualityScoreResponse.attributeTypeMap;
  }
}
