/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FinancialAccountType } from './financialAccountType';
import { FinancialUserProfileType } from './financialUserProfileType';
import { PlaidAccountTransaction } from './plaidAccountTransaction';

/**
 * Add transactions to an account.
 */
export class AddTransactionsToManuallyLinkedAccountRequest {
  'accountId': string;
  'transactions': Array<PlaidAccountTransaction>;
  'profileType': FinancialUserProfileType;
  'financialAccountType'?: FinancialAccountType;
  'userId': string;
  'linkId': string;
  /**
   * Organization identifier for multi-org support
   */
  'orgId': string;
  /**
   * Tenant identifier for multi-tenancy support
   */
  'tenantId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'accountId',
      baseName: 'accountId',
      type: 'string',
    },
    {
      name: 'transactions',
      baseName: 'transactions',
      type: 'Array<PlaidAccountTransaction>',
    },
    {
      name: 'profileType',
      baseName: 'profileType',
      type: 'FinancialUserProfileType',
    },
    {
      name: 'financialAccountType',
      baseName: 'financialAccountType',
      type: 'FinancialAccountType',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'linkId',
      baseName: 'linkId',
      type: 'string',
    },
    {
      name: 'orgId',
      baseName: 'orgId',
      type: 'string',
    },
    {
      name: 'tenantId',
      baseName: 'tenantId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return AddTransactionsToManuallyLinkedAccountRequest.attributeTypeMap;
  }
}

export namespace AddTransactionsToManuallyLinkedAccountRequest {}
