/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Types of events recorded in audit logs.   - AUDIT_EVENT_TYPE_UNSPECIFIED: Default unspecified audit event.  - AUDIT_EVENT_TYPE_CREATE: Event indicating creation.  - AUDIT_EVENT_TYPE_UPDATE: Event indicating update.  - AUDIT_EVENT_TYPE_DELETE: Event indicating deletion.  - AUDIT_EVENT_TYPE_LOGIN: Login event.  - AUDIT_EVENT_TYPE_LOGOUT: Logout event.  - AUDIT_EVENT_TYPE_ACCESS: Resource access event.  - AUDIT_EVENT_TYPE_PERMISSION_CHANGE: Permission change event.  - AUDIT_EVENT_TYPE_PASSWORD_CHANGE: Password change event.
 */
export enum AuditEventType {
  Unspecified = <any>'AUDIT_EVENT_TYPE_UNSPECIFIED',
  Create = <any>'AUDIT_EVENT_TYPE_CREATE',
  Update = <any>'AUDIT_EVENT_TYPE_UPDATE',
  Delete = <any>'AUDIT_EVENT_TYPE_DELETE',
  Login = <any>'AUDIT_EVENT_TYPE_LOGIN',
  Logout = <any>'AUDIT_EVENT_TYPE_LOGOUT',
  Access = <any>'AUDIT_EVENT_TYPE_ACCESS',
  PermissionChange = <any>'AUDIT_EVENT_TYPE_PERMISSION_CHANGE',
  PasswordChange = <any>'AUDIT_EVENT_TYPE_PASSWORD_CHANGE',
  PaymentProcessed = <any>'AUDIT_EVENT_TYPE_PAYMENT_PROCESSED',
  KycUpdated = <any>'AUDIT_EVENT_TYPE_KYC_UPDATED',
  ComplianceCheck = <any>'AUDIT_EVENT_TYPE_COMPLIANCE_CHECK',
  TransactionFlagged = <any>'AUDIT_EVENT_TYPE_TRANSACTION_FLAGGED',
  LimitUpdated = <any>'AUDIT_EVENT_TYPE_LIMIT_UPDATED',
}
