/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountStatements } from './accountStatements';
import { BankAccountStatus } from './bankAccountStatus';
import { BankAccountType } from './bankAccountType';
import { PlaidAccountRecurringTransaction } from './plaidAccountRecurringTransaction';
import { PlaidAccountTransaction } from './plaidAccountTransaction';
import { Pocket } from './pocket';

export class BankAccount {
  'id'?: string;
  'userId'?: string;
  'name'?: string;
  'number'?: string;
  'type': BankAccountType;
  'balance': number;
  'currency': string;
  'currentFunds': number;
  'balanceLimit'?: string;
  'pockets'?: Array<Pocket>;
  'plaidAccountId'?: string;
  'subtype'?: string;
  'status'?: BankAccountStatus;
  'transactions'?: Array<PlaidAccountTransaction>;
  'recurringTransactions'?: Array<PlaidAccountRecurringTransaction>;
  'statements'?: Array<AccountStatements>;
  'plaidAccountType'?: string;
  'createdAt'?: Date;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'number',
      baseName: 'number',
      type: 'string',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'BankAccountType',
    },
    {
      name: 'balance',
      baseName: 'balance',
      type: 'number',
    },
    {
      name: 'currency',
      baseName: 'currency',
      type: 'string',
    },
    {
      name: 'currentFunds',
      baseName: 'currentFunds',
      type: 'number',
    },
    {
      name: 'balanceLimit',
      baseName: 'balanceLimit',
      type: 'string',
    },
    {
      name: 'pockets',
      baseName: 'pockets',
      type: 'Array<Pocket>',
    },
    {
      name: 'plaidAccountId',
      baseName: 'plaidAccountId',
      type: 'string',
    },
    {
      name: 'subtype',
      baseName: 'subtype',
      type: 'string',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'BankAccountStatus',
    },
    {
      name: 'transactions',
      baseName: 'transactions',
      type: 'Array<PlaidAccountTransaction>',
    },
    {
      name: 'recurringTransactions',
      baseName: 'recurringTransactions',
      type: 'Array<PlaidAccountRecurringTransaction>',
    },
    {
      name: 'statements',
      baseName: 'statements',
      type: 'Array<AccountStatements>',
    },
    {
      name: 'plaidAccountType',
      baseName: 'plaidAccountType',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return BankAccount.attributeTypeMap;
  }
}

export namespace BankAccount {}
