/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TeamMember } from './teamMember';

export class BulkAddTeamMembersBody {
  'organizationId': string;
  'tenantId': string;
  'members'?: Array<TeamMember>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'organizationId',
      baseName: 'organizationId',
      type: 'string',
    },
    {
      name: 'tenantId',
      baseName: 'tenantId',
      type: 'string',
    },
    {
      name: 'members',
      baseName: 'members',
      type: 'Array<TeamMember>',
    },
  ];

  static getAttributeTypeMap() {
    return BulkAddTeamMembersBody.attributeTypeMap;
  }
}
