/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Comment1 } from './comment1';

/**
 * CommentThread represents a thread of comments on a file. Anchored to specific positions in the document using Tiptap\'s node positions.
 */
export class CommentThread {
  'id'?: string;
  'fileId'?: string;
  'rootComment'?: Comment1;
  'replies'?: Array<Comment1>;
  'status'?: string;
  'createdAt'?: Date;
  'updatedAt'?: Date;
  /**
   * Start position of the comment anchor
   */
  'from'?: number;
  'to'?: number;
  'versionId'?: string;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'fileId',
      baseName: 'fileId',
      type: 'string',
    },
    {
      name: 'rootComment',
      baseName: 'rootComment',
      type: 'Comment1',
    },
    {
      name: 'replies',
      baseName: 'replies',
      type: 'Array<Comment1>',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'Date',
    },
    {
      name: 'from',
      baseName: 'from',
      type: 'number',
    },
    {
      name: 'to',
      baseName: 'to',
      type: 'number',
    },
    {
      name: 'versionId',
      baseName: 'versionId',
      type: 'string',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return CommentThread.attributeTypeMap;
  }
}
