/**
 * Lead Scraping Service API
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@vector.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConflictInfo {
  'resourceType'?: string;
  'identifier'?: string;
  'conflictReason'?: string;
  'createdAt'?: Date;
  'createdBy'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'resourceType',
      baseName: 'resourceType',
      type: 'string',
    },
    {
      name: 'identifier',
      baseName: 'identifier',
      type: 'string',
    },
    {
      name: 'conflictReason',
      baseName: 'conflictReason',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'createdBy',
      baseName: 'createdBy',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ConflictInfo.attributeTypeMap;
  }
}
