/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FinancialUserProfileType } from './financialUserProfileType';
import { Link } from './link';

export class CreateManualLinkRequest {
  'userId': string;
  'manualAccountLink': Link;
  'profileType': FinancialUserProfileType;
  /**
   * Organization identifier for multi-org support
   */
  'orgId': string;
  /**
   * Tenant identifier for multi-tenancy support
   */
  'tenantId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'manualAccountLink',
      baseName: 'manualAccountLink',
      type: 'Link',
    },
    {
      name: 'profileType',
      baseName: 'profileType',
      type: 'FinancialUserProfileType',
    },
    {
      name: 'orgId',
      baseName: 'orgId',
      type: 'string',
    },
    {
      name: 'tenantId',
      baseName: 'tenantId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return CreateManualLinkRequest.attributeTypeMap;
  }
}

export namespace CreateManualLinkRequest {}
