/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * CreateUserProfileResponse represents the response object returned after a successful user profile creation request. This message encapsulates the essential information that confirms the creation of a new social user profile.
 */
export class CreateUserProfileResponse {
  /**
   * Unique virtual identifier for the newly created user profile
   */
  'virtualProfileId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'virtualProfileId',
      baseName: 'virtualProfileId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return CreateUserProfileResponse.attributeTypeMap;
  }
}
