/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkspaceCompliance } from './workspaceCompliance';

/**
 * CreateWorkspaceComplianceResponse contains the newly created or updated compliance settings.  The response includes the complete compliance configuration that was applied, allowing verification that all settings were properly saved.  Example: ```protobuf message response {   compliance: {     id: 123,     retention_period_days: 90,     require_2fa: true,     audit_logging_enabled: true,     created_at: \"2023-06-01T10:30:00Z\"   } } ```
 */
export class CreateWorkspaceComplianceResponse {
  'compliance'?: WorkspaceCompliance;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'compliance',
      baseName: 'compliance',
      type: 'WorkspaceCompliance',
    },
  ];

  static getAttributeTypeMap() {
    return CreateWorkspaceComplianceResponse.attributeTypeMap;
  }
}
