/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * The Deduction object is used to represent an array of the wages withheld from total earnings for the purpose of paying taxes.
 */
export class Deduction {
  'id'?: string;
  /**
   * The third-party API ID of the matching object.
   */
  'remoteId'?: string;
  /**
   * The deduction\'s name.
   */
  'name'?: string;
  /**
   * The amount of money that is withheld from an employee\'s gross pay by the employee.
   */
  'employeeDeduction'?: number;
  /**
   * The amount of money that is withheld on behalf of an employee by the company.
   */
  'companyDeduction'?: number;
  /**
   * Indicates whether or not this object has been deleted in the third party platform.
   */
  'remoteWasDeleted'?: boolean;
  'createdAt'?: Date;
  'modifiedAt'?: Date;
  /**
   * The payroll being run.
   */
  'payrollRunMergeAccountId'?: string;
  'mergeAccountId'?: string;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'remoteId',
      baseName: 'remoteId',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'employeeDeduction',
      baseName: 'employeeDeduction',
      type: 'number',
    },
    {
      name: 'companyDeduction',
      baseName: 'companyDeduction',
      type: 'number',
    },
    {
      name: 'remoteWasDeleted',
      baseName: 'remoteWasDeleted',
      type: 'boolean',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'modifiedAt',
      baseName: 'modifiedAt',
      type: 'Date',
    },
    {
      name: 'payrollRunMergeAccountId',
      baseName: 'payrollRunMergeAccountId',
      type: 'string',
    },
    {
      name: 'mergeAccountId',
      baseName: 'mergeAccountId',
      type: 'string',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return Deduction.attributeTypeMap;
  }
}
