/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DependentRelationship } from './dependentRelationship';
import { Gender } from './gender';
import { LocationAddress } from './locationAddress';

export class Dependents {
  'id'?: string;
  /**
   * The third-party API ID of the matching object.
   */
  'remoteId'?: string;
  /**
   * The employee\'s first name.
   */
  'firstName'?: string;
  /**
   * The employee\'s last name.
   */
  'lastName'?: string;
  'middleName'?: string;
  'dependentRelationshipToEmployee'?: DependentRelationship;
  /**
   * The dependent\'s date of birth.
   */
  'dateOfBirth'?: Date;
  'gender'?: Gender;
  'phoneNumber'?: string;
  'homeLocation'?: LocationAddress;
  'isStudent'?: boolean;
  /**
   * The dependents\'s social security number.
   */
  'ssn'?: string;
  /**
   * Indicates whether or not this object has been deleted in the third party platform.
   */
  'remoteWasDeleted'?: boolean;
  'createdAt'?: Date;
  'modifiedAt'?: Date;
  'mergeAccountId'?: string;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'remoteId',
      baseName: 'remoteId',
      type: 'string',
    },
    {
      name: 'firstName',
      baseName: 'firstName',
      type: 'string',
    },
    {
      name: 'lastName',
      baseName: 'lastName',
      type: 'string',
    },
    {
      name: 'middleName',
      baseName: 'middleName',
      type: 'string',
    },
    {
      name: 'dependentRelationshipToEmployee',
      baseName: 'dependentRelationshipToEmployee',
      type: 'DependentRelationship',
    },
    {
      name: 'dateOfBirth',
      baseName: 'dateOfBirth',
      type: 'Date',
    },
    {
      name: 'gender',
      baseName: 'gender',
      type: 'Gender',
    },
    {
      name: 'phoneNumber',
      baseName: 'phoneNumber',
      type: 'string',
    },
    {
      name: 'homeLocation',
      baseName: 'homeLocation',
      type: 'LocationAddress',
    },
    {
      name: 'isStudent',
      baseName: 'isStudent',
      type: 'boolean',
    },
    {
      name: 'ssn',
      baseName: 'ssn',
      type: 'string',
    },
    {
      name: 'remoteWasDeleted',
      baseName: 'remoteWasDeleted',
      type: 'boolean',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'modifiedAt',
      baseName: 'modifiedAt',
      type: 'Date',
    },
    {
      name: 'mergeAccountId',
      baseName: 'mergeAccountId',
      type: 'string',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return Dependents.attributeTypeMap;
  }
}

export namespace Dependents {}
