/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Event types associated with system resource usage or quotas.   - EVENT_TYPE_UNSPECIFIED: Default unspecified event type.  - EVENT_TYPE_STORAGE: Event related to data storage.  - EVENT_TYPE_API: Event related to API usage.  - EVENT_TYPE_BANDWIDTH: Event related to data transfer or bandwidth.
 */
export enum EventType {
  Unspecified = <any>'EVENT_TYPE_UNSPECIFIED',
  Storage = <any>'EVENT_TYPE_STORAGE',
  Api = <any>'EVENT_TYPE_API',
  Bandwidth = <any>'EVENT_TYPE_BANDWIDTH',
}
