/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SharePermission } from './sharePermission';

/**
 * FileSharing manages link sharing for files.  Features: - Secure link generation - Access permissions - Expiration settings - Access tracking
 */
export class FileSharing {
  'id'?: string;
  'fileId'?: string;
  'sharedLink'?: string;
  'permissionLevel'?: SharePermission;
  'expiresAt'?: Date;
  'createdAt'?: Date;
  'lastAccessed'?: Date;
  'isActive'?: boolean;
  'password'?: string;
  'maxAccesses'?: number;
  'accessCount'?: number;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'fileId',
      baseName: 'fileId',
      type: 'string',
    },
    {
      name: 'sharedLink',
      baseName: 'sharedLink',
      type: 'string',
    },
    {
      name: 'permissionLevel',
      baseName: 'permissionLevel',
      type: 'SharePermission',
    },
    {
      name: 'expiresAt',
      baseName: 'expiresAt',
      type: 'Date',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'lastAccessed',
      baseName: 'lastAccessed',
      type: 'Date',
    },
    {
      name: 'isActive',
      baseName: 'isActive',
      type: 'boolean',
    },
    {
      name: 'password',
      baseName: 'password',
      type: 'string',
    },
    {
      name: 'maxAccesses',
      baseName: 'maxAccesses',
      type: 'number',
    },
    {
      name: 'accessCount',
      baseName: 'accessCount',
      type: 'number',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return FileSharing.attributeTypeMap;
  }
}

export namespace FileSharing {}
