/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BackgroundJobStatus } from './backgroundJobStatus';

/**
 * GetBackgroundJobStatusResponse represents the current status of a background job. Provides information about job progress and estimated completion.  Fields: - status: Current status of the background job - estimated_completion_time: Expected completion timestamp - job_id: The unique identifier of the job being tracked
 */
export class GetBackgroundJobStatusResponse {
  'status'?: BackgroundJobStatus;
  'estimatedCompletionTime'?: Date;
  'jobId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'status',
      baseName: 'status',
      type: 'BackgroundJobStatus',
    },
    {
      name: 'estimatedCompletionTime',
      baseName: 'estimatedCompletionTime',
      type: 'Date',
    },
    {
      name: 'jobId',
      baseName: 'jobId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return GetBackgroundJobStatusResponse.attributeTypeMap;
  }
}

export namespace GetBackgroundJobStatusResponse {}
