/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Defines a message named GetLinkTokenResponse.
 */
export class GetMergeLinkTokenResponse {
  /**
   * A string field named \"link_token\" with field number 1.
   */
  'linkToken'?: string;
  /**
   * A string field named \"integration_name\" with field number 2.
   */
  'integrationName'?: string;
  /**
   * A string field named \"magic_link_url\" with field number 3.
   */
  'magicLinkUrl'?: string;
  /**
   * A string field named \"end_user_origin_id\" with field number 4.
   */
  'endUserOriginId'?: string;
  /**
   * A string field named \"organization_name\" with field number 5.
   */
  'organizationName'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'linkToken',
      baseName: 'linkToken',
      type: 'string',
    },
    {
      name: 'integrationName',
      baseName: 'integrationName',
      type: 'string',
    },
    {
      name: 'magicLinkUrl',
      baseName: 'magicLinkUrl',
      type: 'string',
    },
    {
      name: 'endUserOriginId',
      baseName: 'endUserOriginId',
      type: 'string',
    },
    {
      name: 'organizationName',
      baseName: 'organizationName',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return GetMergeLinkTokenResponse.attributeTypeMap;
  }
}
