/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetWorkflowExecutionStatusResponse {
  'workflowId'?: string;
  'status'?: string;
  'runId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'workflowId',
      baseName: 'workflowId',
      type: 'string',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
    },
    {
      name: 'runId',
      baseName: 'runId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return GetWorkflowExecutionStatusResponse.attributeTypeMap;
  }
}
