/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HrisLinkedAccount } from './hrisLinkedAccount';
import { MergeLinkedAccountToken } from './mergeLinkedAccountToken';

export class HrisIntegrationMergeLink {
  'id'?: string;
  'integration'?: string;
  'integrationSlug'?: string;
  'category'?: string;
  'endUserOriginId'?: string;
  'endUserOrganizationName'?: string;
  'endUserEmailAddress'?: string;
  'status'?: string;
  'webhookListenerUrl'?: string;
  'isDuplicate'?: boolean;
  'token'?: MergeLinkedAccountToken;
  'integrationName'?: string;
  'integrationImage'?: string;
  'integrationSquareImage'?: string;
  'account'?: HrisLinkedAccount;
  'mergeLinkedAccountId'?: string;
  'lastModifiedAt'?: Date;
  'createdAt'?: Date;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'integration',
      baseName: 'integration',
      type: 'string',
    },
    {
      name: 'integrationSlug',
      baseName: 'integrationSlug',
      type: 'string',
    },
    {
      name: 'category',
      baseName: 'category',
      type: 'string',
    },
    {
      name: 'endUserOriginId',
      baseName: 'endUserOriginId',
      type: 'string',
    },
    {
      name: 'endUserOrganizationName',
      baseName: 'endUserOrganizationName',
      type: 'string',
    },
    {
      name: 'endUserEmailAddress',
      baseName: 'endUserEmailAddress',
      type: 'string',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
    },
    {
      name: 'webhookListenerUrl',
      baseName: 'webhookListenerUrl',
      type: 'string',
    },
    {
      name: 'isDuplicate',
      baseName: 'isDuplicate',
      type: 'boolean',
    },
    {
      name: 'token',
      baseName: 'token',
      type: 'MergeLinkedAccountToken',
    },
    {
      name: 'integrationName',
      baseName: 'integrationName',
      type: 'string',
    },
    {
      name: 'integrationImage',
      baseName: 'integrationImage',
      type: 'string',
    },
    {
      name: 'integrationSquareImage',
      baseName: 'integrationSquareImage',
      type: 'string',
    },
    {
      name: 'account',
      baseName: 'account',
      type: 'HrisLinkedAccount',
    },
    {
      name: 'mergeLinkedAccountId',
      baseName: 'mergeLinkedAccountId',
      type: 'string',
    },
    {
      name: 'lastModifiedAt',
      baseName: 'lastModifiedAt',
      type: 'Date',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return HrisIntegrationMergeLink.attributeTypeMap;
  }
}
