/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InvestmentSecurity {
  'id'?: string;
  'closePrice'?: number;
  'closePriceAsOf'?: string;
  'cusip'?: string;
  'institutionId'?: string;
  'institutionSecurityId'?: string;
  'isCashEquivalent'?: boolean;
  'isin'?: string;
  'isoCurrencyCode'?: string;
  'name'?: string;
  'proxySecurityId'?: string;
  'securityId'?: string;
  'sedol'?: string;
  'tickerSymbol'?: string;
  'type'?: string;
  'unofficialCurrencyCode'?: string;
  'updateDatetime'?: string;
  'createdAt'?: Date;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'closePrice',
      baseName: 'closePrice',
      type: 'number',
    },
    {
      name: 'closePriceAsOf',
      baseName: 'closePriceAsOf',
      type: 'string',
    },
    {
      name: 'cusip',
      baseName: 'cusip',
      type: 'string',
    },
    {
      name: 'institutionId',
      baseName: 'institutionId',
      type: 'string',
    },
    {
      name: 'institutionSecurityId',
      baseName: 'institutionSecurityId',
      type: 'string',
    },
    {
      name: 'isCashEquivalent',
      baseName: 'isCashEquivalent',
      type: 'boolean',
    },
    {
      name: 'isin',
      baseName: 'isin',
      type: 'string',
    },
    {
      name: 'isoCurrencyCode',
      baseName: 'isoCurrencyCode',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'proxySecurityId',
      baseName: 'proxySecurityId',
      type: 'string',
    },
    {
      name: 'securityId',
      baseName: 'securityId',
      type: 'string',
    },
    {
      name: 'sedol',
      baseName: 'sedol',
      type: 'string',
    },
    {
      name: 'tickerSymbol',
      baseName: 'tickerSymbol',
      type: 'string',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
    },
    {
      name: 'unofficialCurrencyCode',
      baseName: 'unofficialCurrencyCode',
      type: 'string',
    },
    {
      name: 'updateDatetime',
      baseName: 'updateDatetime',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return InvestmentSecurity.attributeTypeMap;
  }
}
