/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum LinkStatus {
  Unspecified = <any>'LINK_STATUS_UNSPECIFIED',
  Setup = <any>'LINK_STATUS_SETUP',
  Pending = <any>'LINK_STATUS_PENDING',
  Error = <any>'LINK_STATUS_ERROR',
  Success = <any>'LINK_STATUS_SUCCESS',
  PendingExpiration = <any>'LINK_STATUS_PENDING_EXPIRATION',
  Revoked = <any>'LINK_STATUS_REVOKED',
  ItemLoginRequired = <any>'LINK_STATUS_ITEM_LOGIN_REQUIRED',
}
