/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BankAccount } from './bankAccount';
import { CategoryMetricsFinancialSubProfile } from './categoryMetricsFinancialSubProfile';
import { CreditAccount } from './creditAccount';
import { ExpenseMetricsFinancialSubProfileMetrics } from './expenseMetricsFinancialSubProfileMetrics';
import { FinancialUserProfileType } from './financialUserProfileType';
import { IncomeMetricsFinancialSubProfile } from './incomeMetricsFinancialSubProfile';
import { InvestmentAccount } from './investmentAccount';
import { LocationFinancialSubProfile } from './locationFinancialSubProfile';
import { MerchantMetricsFinancialSubProfile } from './merchantMetricsFinancialSubProfile';
import { MortgageAccount } from './mortgageAccount';
import { PaymentChannelMetricsFinancialSubProfile } from './paymentChannelMetricsFinancialSubProfile';
import { StudentLoanAccount } from './studentLoanAccount';

/**
 * MelodyFinancialContext represents the financial context of a user. This message is used to represent the financial context of a user.
 */
export class MelodyFinancialContext {
  'categories'?: Array<CategoryMetricsFinancialSubProfile>;
  'expenses'?: Array<ExpenseMetricsFinancialSubProfileMetrics>;
  'income'?: Array<IncomeMetricsFinancialSubProfile>;
  'locations'?: Array<LocationFinancialSubProfile>;
  'merchants'?: Array<MerchantMetricsFinancialSubProfile>;
  'paymentChannels'?: Array<PaymentChannelMetricsFinancialSubProfile>;
  'bankAccounts'?: Array<BankAccount>;
  'investmentAccounts'?: Array<InvestmentAccount>;
  'creditAccounts'?: Array<CreditAccount>;
  'mortgageLoanAccounts'?: Array<MortgageAccount>;
  'studentLoanAccounts'?: Array<StudentLoanAccount>;
  'financialUserProfileType'?: FinancialUserProfileType;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'categories',
      baseName: 'categories',
      type: 'Array<CategoryMetricsFinancialSubProfile>',
    },
    {
      name: 'expenses',
      baseName: 'expenses',
      type: 'Array<ExpenseMetricsFinancialSubProfileMetrics>',
    },
    {
      name: 'income',
      baseName: 'income',
      type: 'Array<IncomeMetricsFinancialSubProfile>',
    },
    {
      name: 'locations',
      baseName: 'locations',
      type: 'Array<LocationFinancialSubProfile>',
    },
    {
      name: 'merchants',
      baseName: 'merchants',
      type: 'Array<MerchantMetricsFinancialSubProfile>',
    },
    {
      name: 'paymentChannels',
      baseName: 'paymentChannels',
      type: 'Array<PaymentChannelMetricsFinancialSubProfile>',
    },
    {
      name: 'bankAccounts',
      baseName: 'bankAccounts',
      type: 'Array<BankAccount>',
    },
    {
      name: 'investmentAccounts',
      baseName: 'investmentAccounts',
      type: 'Array<InvestmentAccount>',
    },
    {
      name: 'creditAccounts',
      baseName: 'creditAccounts',
      type: 'Array<CreditAccount>',
    },
    {
      name: 'mortgageLoanAccounts',
      baseName: 'mortgageLoanAccounts',
      type: 'Array<MortgageAccount>',
    },
    {
      name: 'studentLoanAccounts',
      baseName: 'studentLoanAccounts',
      type: 'Array<StudentLoanAccount>',
    },
    {
      name: 'financialUserProfileType',
      baseName: 'financialUserProfileType',
      type: 'FinancialUserProfileType',
    },
  ];

  static getAttributeTypeMap() {
    return MelodyFinancialContext.attributeTypeMap;
  }
}

export namespace MelodyFinancialContext {}
