/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FinancialUserProfileType } from './financialUserProfileType';

/**
 * MonthlySavings This message is used to represent the monthly savings of a user.
 */
export class MonthlySavings {
  'month'?: number;
  'netSavings'?: number;
  'userId'?: string;
  'profileType'?: FinancialUserProfileType;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'month',
      baseName: 'month',
      type: 'number',
    },
    {
      name: 'netSavings',
      baseName: 'netSavings',
      type: 'number',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'profileType',
      baseName: 'profileType',
      type: 'FinancialUserProfileType',
    },
  ];

  static getAttributeTypeMap() {
    return MonthlySavings.attributeTypeMap;
  }
}

export namespace MonthlySavings {}
