/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BusinessAccount } from './businessAccount';
import { TransferReason } from './transferReason';

export class OwnershipTransfer {
  'id'?: string;
  'previousAdmin'?: BusinessAccount;
  'newAdmin'?: BusinessAccount;
  'reason'?: TransferReason;
  'transferNotes'?: string;
  'transferredAt'?: Date;
  'supportingDocuments'?: Array<string>;
  'isTemporary'?: boolean;
  'revertDate'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'previousAdmin',
      baseName: 'previousAdmin',
      type: 'BusinessAccount',
    },
    {
      name: 'newAdmin',
      baseName: 'newAdmin',
      type: 'BusinessAccount',
    },
    {
      name: 'reason',
      baseName: 'reason',
      type: 'TransferReason',
    },
    {
      name: 'transferNotes',
      baseName: 'transferNotes',
      type: 'string',
    },
    {
      name: 'transferredAt',
      baseName: 'transferredAt',
      type: 'Date',
    },
    {
      name: 'supportingDocuments',
      baseName: 'supportingDocuments',
      type: 'Array<string>',
    },
    {
      name: 'isTemporary',
      baseName: 'isTemporary',
      type: 'boolean',
    },
    {
      name: 'revertDate',
      baseName: 'revertDate',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return OwnershipTransfer.attributeTypeMap;
  }
}

export namespace OwnershipTransfer {}
