/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * The type of the payroll run Possible values include: REGULAR, OFF_CYCLE, CORRECTION, TERMINATION, SIGN_ON_BONUS. In cases where there is no clear mapping, the original value passed through will be returned.
 */
export enum PayrollRunType {
  Unspecified = <any>'PAYROLL_RUN_TYPE_UNSPECIFIED',
  Regular = <any>'PAYROLL_RUN_TYPE_REGULAR',
  OffCycle = <any>'PAYROLL_RUN_TYPE_OFF_CYCLE',
  Correction = <any>'PAYROLL_RUN_TYPE_CORRECTION',
  Termination = <any>'PAYROLL_RUN_TYPE_TERMINATION',
  SignOnBonus = <any>'PAYROLL_RUN_TYPE_SIGN_ON_BONUS',
}
