/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * - PERMISSION_SCOPE_UNSPECIFIED: Default value as required by proto3  - PERMISSION_SCOPE_TEAM: Permission applies to the team only  - PERMISSION_SCOPE_IMMEDIATE_HIERARCHY: Permission applies to the team and immediate sub-teams  - PERMISSION_SCOPE_FULL_HIERARCHY: Permission applies to the team and all sub-teams  - PERMISSION_SCOPE_RESOURCE_SPECIFIC: Permission applies to specific resources only
 */
export enum PermissionScope {
  Unspecified = <any>'PERMISSION_SCOPE_UNSPECIFIED',
  Team = <any>'PERMISSION_SCOPE_TEAM',
  ImmediateHierarchy = <any>'PERMISSION_SCOPE_IMMEDIATE_HIERARCHY',
  FullHierarchy = <any>'PERMISSION_SCOPE_FULL_HIERARCHY',
  ResourceSpecific = <any>'PERMISSION_SCOPE_RESOURCE_SPECIFIC',
}
