/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Represents types of accounts linked to a profile.   - PROFILE_TYPE_UNSPECIFIED: Default unspecified profile type.  - PROFILE_TYPE_USER: Individual user profile.  - PROFILE_TYPE_BUSINESS: Business profile.
 */
export enum ProfileType {
  Unspecified = <any>'PROFILE_TYPE_UNSPECIFIED',
  User = <any>'PROFILE_TYPE_USER',
  Business = <any>'PROFILE_TYPE_BUSINESS',
}
