/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Request for reading business transactions with pagination and time filtering.
 */
export class ReadBusinessTransactionsRequest {
  /**
   * The ID of the user whose transactions are to be fetched.
   */
  'authZeroUserId': string;
  /**
   * The ID of the accounting account whose transactions are to be fetched.
   */
  'linkedAccountingAccountId': string;
  /**
   * The page number of the paginated results.
   */
  'pageNumber': string;
  /**
   * The number of items to be returned per page.
   */
  'pageSize': string;
  'orgId': string;
  'tenantId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'authZeroUserId',
      baseName: 'authZeroUserId',
      type: 'string',
    },
    {
      name: 'linkedAccountingAccountId',
      baseName: 'linkedAccountingAccountId',
      type: 'string',
    },
    {
      name: 'pageNumber',
      baseName: 'pageNumber',
      type: 'string',
    },
    {
      name: 'pageSize',
      baseName: 'pageSize',
      type: 'string',
    },
    {
      name: 'orgId',
      baseName: 'orgId',
      type: 'string',
    },
    {
      name: 'tenantId',
      baseName: 'tenantId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ReadBusinessTransactionsRequest.attributeTypeMap;
  }
}
