/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReadCashFlowStatementsRequest {
  'authZeroUserId': string;
  'acountingIntegrationMergeLinkId': string;
  'startDate': Date;
  'endDate': Date;
  'pageSize': number;
  'pageNumber': number;
  'orgId': string;
  'tenantId': string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'authZeroUserId',
      baseName: 'authZeroUserId',
      type: 'string',
    },
    {
      name: 'acountingIntegrationMergeLinkId',
      baseName: 'acountingIntegrationMergeLinkId',
      type: 'string',
    },
    {
      name: 'startDate',
      baseName: 'startDate',
      type: 'Date',
    },
    {
      name: 'endDate',
      baseName: 'endDate',
      type: 'Date',
    },
    {
      name: 'pageSize',
      baseName: 'pageSize',
      type: 'number',
    },
    {
      name: 'pageNumber',
      baseName: 'pageNumber',
      type: 'number',
    },
    {
      name: 'orgId',
      baseName: 'orgId',
      type: 'string',
    },
    {
      name: 'tenantId',
      baseName: 'tenantId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ReadCashFlowStatementsRequest.attributeTypeMap;
  }
}
