/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum RegulatoryStatus {
  Unspecified = <any>'REGULATORY_STATUS_UNSPECIFIED',
  Licensed = <any>'REGULATORY_STATUS_LICENSED',
  Pending = <any>'REGULATORY_STATUS_PENDING',
  Exempt = <any>'REGULATORY_STATUS_EXEMPT',
}
