/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * Levels of severity for logging or alerting.   - SEVERITY_LEVEL_UNSPECIFIED: Default unspecified level.  - SEVERITY_LEVEL_INFO: Informational message.  - SEVERITY_LEVEL_WARNING: Warning message.  - SEVERITY_LEVEL_ERROR: Error message.  - SEVERITY_LEVEL_CRITICAL: Critical failure message.
 */
export enum SeverityLevel {
  Unspecified = <any>'SEVERITY_LEVEL_UNSPECIFIED',
  Info = <any>'SEVERITY_LEVEL_INFO',
  Warning = <any>'SEVERITY_LEVEL_WARNING',
  Error = <any>'SEVERITY_LEVEL_ERROR',
  Critical = <any>'SEVERITY_LEVEL_CRITICAL',
}
