/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountType } from './accountType';

export class SocialProfileMetadata {
  'profileType'?: AccountType;
  'profileId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'profileType',
      baseName: 'profileType',
      type: 'AccountType',
    },
    {
      name: 'profileId',
      baseName: 'profileId',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return SocialProfileMetadata.attributeTypeMap;
  }
}

export namespace SocialProfileMetadata {}
