/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActorType } from './actorType';
import { BusinessAccount } from './businessAccount';
import { Role } from './role';
import { TeamInviteStatus } from './teamInviteStatus';

export class TeamInvites {
  'id'?: string;
  'inviteeEmail': string;
  'role'?: Role;
  'inviteToken': string;
  'inviterType'?: ActorType;
  'inviter'?: BusinessAccount;
  'expiresAt'?: Date;
  'createdAt'?: Date;
  'updatedAt'?: Date;
  'inviteMessage'?: string;
  'respondedAt'?: Date;
  'metadata'?: object;
  'status'?: TeamInviteStatus;
  'deletedAt'?: Date;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'inviteeEmail',
      baseName: 'inviteeEmail',
      type: 'string',
    },
    {
      name: 'role',
      baseName: 'role',
      type: 'Role',
    },
    {
      name: 'inviteToken',
      baseName: 'inviteToken',
      type: 'string',
    },
    {
      name: 'inviterType',
      baseName: 'inviterType',
      type: 'ActorType',
    },
    {
      name: 'inviter',
      baseName: 'inviter',
      type: 'BusinessAccount',
    },
    {
      name: 'expiresAt',
      baseName: 'expiresAt',
      type: 'Date',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'Date',
    },
    {
      name: 'inviteMessage',
      baseName: 'inviteMessage',
      type: 'string',
    },
    {
      name: 'respondedAt',
      baseName: 'respondedAt',
      type: 'Date',
    },
    {
      name: 'metadata',
      baseName: 'metadata',
      type: 'object',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'TeamInviteStatus',
    },
    {
      name: 'deletedAt',
      baseName: 'deletedAt',
      type: 'Date',
    },
  ];

  static getAttributeTypeMap() {
    return TeamInvites.attributeTypeMap;
  }
}

export namespace TeamInvites {}
