/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Thread {
  'id'?: string;
  'postIds'?: Array<string>;
  'parentPostId'?: string;
  'createdAt'?: string;
  'updatedAt'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'postIds',
      baseName: 'postIds',
      type: 'Array<string>',
    },
    {
      name: 'parentPostId',
      baseName: 'parentPostId',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'string',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return Thread.attributeTypeMap;
  }
}
