/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkspaceSharing } from './workspaceSharing';

/**
 * UpdateWorkspaceShareResponse represents the response to a workspace share update request. Contains the updated share object reflecting the applied changes.  Fields: - share: The updated WorkspaceSharing object
 */
export class UpdateWorkspaceShareResponse {
  'share'?: WorkspaceSharing;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'share',
      baseName: 'share',
      type: 'WorkspaceSharing',
    },
  ];

  static getAttributeTypeMap() {
    return UpdateWorkspaceShareResponse.attributeTypeMap;
  }
}
