/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FolderMetadata } from './folderMetadata';

/**
 * UpdateFolderResponse represents the response to a folder metadata update request. This message returns the complete, updated metadata for the modified folder, allowing clients to verify the changes and maintain consistency.  Key features: - Complete updated folder state - Verification of changes - Updated timestamps - Modified relationship data
 */
export class UpdateFolderResponse {
  'folder'?: FolderMetadata;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'folder',
      baseName: 'folder',
      type: 'FolderMetadata',
    },
  ];

  static getAttributeTypeMap() {
    return UpdateFolderResponse.attributeTypeMap;
  }
}
