/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkspaceSharing } from './workspaceSharing';

/**
 * UpdateWorkspaceShareRequest represents a request to update an existing workspace share. Contains the modified share object with updated permissions or settings.  Required Fields: - share: The WorkspaceSharing object containing the updated share configuration
 */
export class UpdateWorkspaceShareRequest {
  'share': WorkspaceSharing;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'share',
      baseName: 'share',
      type: 'WorkspaceSharing',
    },
  ];

  static getAttributeTypeMap() {
    return UpdateWorkspaceShareRequest.attributeTypeMap;
  }
}
