/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorCode1 } from './errorCode1';

export class ValidationErrorMessageResponse1 {
  'code'?: ErrorCode1;
  'message'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'code',
      baseName: 'code',
      type: 'ErrorCode1',
    },
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return ValidationErrorMessageResponse1.attributeTypeMap;
  }
}

export namespace ValidationErrorMessageResponse1 {}
