/**
 * Lead Scraping Service API
 * Vector Lead Scraping Service API - Manages Lead Scraping Jobs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@vector.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorResponse } from './errorResponse';
import { FieldViolation } from './fieldViolation';
import { ResourceValidation } from './resourceValidation';
import { SchemaValidation } from './schemaValidation';
import { ValidationErrorCode } from './validationErrorCode';

/**
 * Represents data validation and business logic errors
 */
export class ValidationErrorMessageResponse {
  'code'?: ValidationErrorCode;
  'message'?: string;
  'fieldViolations'?: Array<FieldViolation>;
  'schemaValidation'?: SchemaValidation;
  'resourceValidation'?: ResourceValidation;
  'errorResponse'?: ErrorResponse;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'code',
      baseName: 'code',
      type: 'ValidationErrorCode',
    },
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
    },
    {
      name: 'fieldViolations',
      baseName: 'fieldViolations',
      type: 'Array<FieldViolation>',
    },
    {
      name: 'schemaValidation',
      baseName: 'schemaValidation',
      type: 'SchemaValidation',
    },
    {
      name: 'resourceValidation',
      baseName: 'resourceValidation',
      type: 'ResourceValidation',
    },
    {
      name: 'errorResponse',
      baseName: 'errorResponse',
      type: 'ErrorResponse',
    },
  ];

  static getAttributeTypeMap() {
    return ValidationErrorMessageResponse.attributeTypeMap;
  }
}

export namespace ValidationErrorMessageResponse {}
