/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkspaceservicehttpTusHeaders {
  /**
   * Standard headers
   */
  'cacheControl'?: string;
  /**
   * Must be application/offset+octet-stream for PATCH
   */
  'contentType'?: string;
  /**
   * URL for the created resource
   */
  'location'?: string;
  /**
   * Comma-separated list of supported checksum algorithms
   */
  'tusChecksumAlgorithm'?: string;
  /**
   * Extension headers
   */
  'tusExtension'?: string;
  /**
   * Maximum allowed upload size
   */
  'tusMaxSize'?: number;
  /**
   * Core protocol headers
   */
  'tusResumable': string;
  /**
   * Comma-separated list of supported protocol versions
   */
  'tusVersion'?: string;
  /**
   * Algorithm and Base64 encoded checksum
   */
  'uploadChecksum'?: string;
  /**
   * Concatenation information
   */
  'uploadConcat'?: string;
  /**
   * Indicates deferred length (must be 1)
   */
  'uploadDeferLength'?: number;
  /**
   * When the upload will expire
   */
  'uploadExpires'?: string;
  /**
   * Total size of the upload
   */
  'uploadLength'?: number;
  /**
   * Base64 encoded key-value pairs
   */
  'uploadMetadata'?: string;
  /**
   * Current offset of the upload
   */
  'uploadOffset'?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'cacheControl',
      baseName: 'cacheControl',
      type: 'string',
    },
    {
      name: 'contentType',
      baseName: 'contentType',
      type: 'string',
    },
    {
      name: 'location',
      baseName: 'location',
      type: 'string',
    },
    {
      name: 'tusChecksumAlgorithm',
      baseName: 'tusChecksumAlgorithm',
      type: 'string',
    },
    {
      name: 'tusExtension',
      baseName: 'tusExtension',
      type: 'string',
    },
    {
      name: 'tusMaxSize',
      baseName: 'tusMaxSize',
      type: 'number',
    },
    {
      name: 'tusResumable',
      baseName: 'tusResumable',
      type: 'string',
    },
    {
      name: 'tusVersion',
      baseName: 'tusVersion',
      type: 'string',
    },
    {
      name: 'uploadChecksum',
      baseName: 'uploadChecksum',
      type: 'string',
    },
    {
      name: 'uploadConcat',
      baseName: 'uploadConcat',
      type: 'string',
    },
    {
      name: 'uploadDeferLength',
      baseName: 'uploadDeferLength',
      type: 'number',
    },
    {
      name: 'uploadExpires',
      baseName: 'uploadExpires',
      type: 'string',
    },
    {
      name: 'uploadLength',
      baseName: 'uploadLength',
      type: 'number',
    },
    {
      name: 'uploadMetadata',
      baseName: 'uploadMetadata',
      type: 'string',
    },
    {
      name: 'uploadOffset',
      baseName: 'uploadOffset',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return WorkspaceservicehttpTusHeaders.attributeTypeMap;
  }
}
