/**
 * User Service API
 * Solomon AI User Service API - Manages user profiles and authentication
 *
 * The version of the OpenAPI document: 1.0
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WorkspaceservicehttpErrorResponse {
  /**
   * A short error code or identifier
   */
  'error'?: string;
  /**
   * Detailed error message explaining the issue
   */
  'message'?: string;
  /**
   * HTTP status code indicating the type of error
   */
  'statusCode'?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'error',
      baseName: 'error',
      type: 'string',
    },
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
    },
    {
      name: 'statusCode',
      baseName: 'status_code',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return WorkspaceservicehttpErrorResponse.attributeTypeMap;
  }
}
