name: Deploy Cloudflare Worker

on:
  workflow_call:
    inputs:
      worker_dir:
        required: true
        type: string
        description: 'Directory path of the worker relative to repository root'
      environment:
        required: false
        type: string
        default: 'production'
        description: 'Environment to deploy to (production/staging/development)'
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
        description: 'Cloudflare API token with Workers deployment permissions'
      CLOUDFLARE_ACCOUNT_ID:
        required: true
        description: 'Cloudflare account ID'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.worker_dir }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs.worker_dir }}
        run: npm ci

      - name: Build worker
        working-directory: ${{ inputs.worker_dir }}
        run: npm run build

      - name: Deploy to Cloudflare Workers
        working-directory: ${{ inputs.worker_dir }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy 