name: Deploy Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      worker:
        description: 'Specific worker to deploy (leave empty to deploy all)'
        required: false
        type: choice
        options:
          - all
          - usage-based-api-gateway
          - gateway

jobs:
  deploy-usage-based-api-gateway:
    if: github.event_name == 'push' || github.event.inputs.worker == 'all' || github.event.inputs.worker == 'usage-based-api-gateway'
    uses: ./.github/workflows/cloudflare-worker-deploy.yml
    with:
      worker_dir: services/usage-based-api-gateway
      environment: production
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-gateway:
    if: github.event_name == 'push' || github.event.inputs.worker == 'all' || github.event.inputs.worker == 'gateway'
    uses: ./.github/workflows/cloudflare-worker-deploy.yml
    with:
      worker_dir: services/gateway
      environment: production
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 