name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'documentation/**'
      - 'version.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docs
        run: ./scripts/build.sh update-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./documentation/autogen/html
          keep_files: true 