name: Deploy Python SDK

on:
  push:
    tags:
      - 'v*'  # This will match any tag that starts with 'v'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get version from tag
        id: get_version
        run: |
          # Strip the 'v' prefix from the tag name
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Update package versions
        run: |
          # Update client SDK version
          cd sdk/client/python-client-sdk
          sed -i "s/version=\".*\"/version=\"$VERSION\"/" setup.py
          cd ../..
          # Update server SDK version
          cd server/python
          sed -i "s/version=\".*\"/version=\"$VERSION\"/" setup.py
          cd ../../..
          # Commit changes
          git add sdk/client/python-client-sdk/setup.py sdk/server/python/setup.py
          git commit -m "chore: update Python SDK versions to $VERSION [skip ci]"
          git push origin HEAD:main

      - name: Build client SDK
        run: |
          cd sdk/client/python-client-sdk
          python -m pip install --upgrade build
          python -m build
          
      - name: Build server SDK
        run: |
          cd sdk/server/python
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: sdk/client/python-client-sdk/dist/
          verify-metadata: false
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_TOKEN }}
        continue-on-error: true

      - name: Publish Server SDK to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: sdk/server/python/dist/
          verify-metadata: false
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_TOKEN }} 
        continue-on-error: true
