name: Deploy TypeScript SDK

on:
  push:
    tags:
      - 'v*'  # This will match any tag that starts with 'v'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get version from tag
        id: get_version
        run: |
          # Strip the 'v' prefix from the tag name
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd sdk/client/client-typescript-sdk
          npm ci
          cd ../client-node-sdk
          npm ci

      - name: Update package versions
        run: |
          # First checkout main branch
          git fetch origin main
          git checkout main
          
          cd sdk/client/client-typescript-sdk
          npm version $VERSION --no-git-tag-version
          cd ../client-node-sdk
          npm version $VERSION --no-git-tag-version
          cd ../../..
          
          # Commit and push changes
          git add sdk/client/client-typescript-sdk/package.json sdk/client/client-node-sdk/package.json
          git commit -m "chore: update SDK versions to $VERSION [skip ci]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main

      - name: Build and test
        run: ./scripts/build.sh test

      - name: Publish client-typescript-sdk
        run: |
          cd sdk/client/client-typescript-sdk
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish client-node-sdk
        run: |
          cd sdk/client/client-node-sdk
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 