name: Deploy Python SDK

on:
  push:
    branches: [ main ]
    paths:
      - 'sdk/client/python-client-sdk/**'
      - 'sdk/server/python/**'
      - 'version.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read versions
        run: |
          PY_VERSION=$(grep 'python:' version.yaml | awk '{print $2}')
          echo "PY_VERSION=$PY_VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build client SDK
        run: |
          cd sdk/client/python-client-sdk
          python -m pip install --upgrade build
          python -m build
          
      - name: Build server SDK
        run: |
          cd sdk/server/python
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: |
            sdk/client/python-client-sdk/dist/*
            sdk/server/python/dist/*
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_TOKEN }} 